[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$WorkRoot
)
# Independent offline tests of the executed test-environment lifecycle entry points: step order, journal written
# before each side effect, partial-failure preservation, retry refusal and cleanup preview/execute separation.
# Each run starts the real New-TestDatabase.ps1 or Remove-TestEnvironment.ps1 in a separate Windows PowerShell
# process through a harness generated below the suite root. Aliases win over functions in PowerShell command
# lookup, so the harness shadows only the SQL, Windows identity/account, ACL/DPAPI/credential and process
# boundaries and verifies that shadowing before the entry point runs. Journal writes, manifest validation, the
# lock file and the installer core stay real. The approved contract exists only in harness memory.
. (Join-Path $PSScriptRoot 'TestSupport.ps1')
$null = Initialize-TestSuite -WorkRoot $WorkRoot -Suite 'test-environment-lifecycle'
. (Join-Path $script:ToolRoot 'test-environment/Environment.Common.ps1')
Set-OfflineStubs

$database = 'Dawnholder_Dev_Fixture'
$executorSid = 'S-1-5-21-1-2-3-1001'
$recoveryAccountSid = 'S-1-5-21-1-2-3-1005'
# The harness reports this created-database identity; cleanup settlements must name the same GUID.
$fixtureDatabaseGuid = '6F9619FF-8B86-D011-B42D-00C04FC964FF'
$script:AllRuns = New-Object 'Collections.Generic.List[object]'

$harnessSource = @'
param(
    [Parameter(Mandatory)][string]$ScenarioRoot,
    [Parameter(Mandatory)][string]$RunName
)
# Generated by TestEnvironmentLifecycle.Tests.ps1. Runs one product entry point with shadowed I/O boundaries.
# Exit 3: a boundary was not shadowed. Exit 4: a path left the scenario root. The product did not run in both.
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$scenario = [IO.File]::ReadAllText((Join-Path $ScenarioRoot 'scenario.json')) | ConvertFrom-Json
$request = [IO.File]::ReadAllText((Join-Path $ScenarioRoot ($RunName + '.request.json'))) | ConvertFrom-Json
$toolRoot = $scenario.ToolRoot
$global:HarnessRoot = [IO.Path]::GetFullPath($ScenarioRoot).TrimEnd('\')
$global:HarnessRun = $RunName
$global:HarnessCallsPath = Join-Path $ScenarioRoot 'calls.jsonl'
$global:HarnessBehavior = $request.Behavior

# Product definitions: the executor stub keeps the real approval check, and the probe below needs them loaded.
. (Join-Path $toolRoot 'test-environment/Environment.Common.ps1')

# The approved contract is the on-disk draft plus G2, validated by the product and never written to disk.
$contract = [IO.File]::ReadAllText($scenario.PlanPath) | ConvertFrom-Json
$contract.ExecutionApproved = $true
$contract.G2 = 'fixture-g2-in-memory'
Assert-TestEnvironmentApprovalPlan -Plan $contract
$contract | Add-Member -MemberType NoteProperty -Name ApprovalPlanPath -Value $scenario.PlanPath
$contract | Add-Member -MemberType NoteProperty -Name ApprovalPlanHash -Value $scenario.PlanHash
$global:HarnessContract = $contract

function global:Assert-HarnessContained {
    param([string]$Path)
    $full = [IO.Path]::GetFullPath($Path)
    if (-not $full.StartsWith($global:HarnessRoot + '\', [StringComparison]::OrdinalIgnoreCase)) {
        throw "Offline harness: path outside the scenario root: $full"
    }
}

function global:Get-HarnessJournal {
    # The on-disk manifest exactly as the product left it when a stubbed side effect was requested.
    $path = $global:HarnessContract.ManifestPath
    if (-not [IO.File]::Exists($path)) {
        return 'absent'
    }
    $manifest = [IO.File]::ReadAllText($path) | ConvertFrom-Json
    $steps = @($manifest.Steps | ForEach-Object { $_.Name + ':' + $_.Status })
    if ($null -ne $manifest.Cleanup) {
        $steps += @($manifest.Cleanup.Steps | ForEach-Object { 'Cleanup.' + $_.Name + ':' + $_.Status })
    }
    return 'State=' + $manifest.State + ';' + ($steps -join ',')
}

function global:Write-HarnessCall {
    param([string]$Name, [string]$Detail = '')
    $entry = [pscustomobject]@{
        Run = $global:HarnessRun
        Name = $Name
        Detail = $Detail
        Journal = Get-HarnessJournal
    }
    $line = (ConvertTo-Json -InputObject $entry -Compress) + "`n"
    [IO.File]::AppendAllText($global:HarnessCallsPath, $line)
}

function global:New-HarnessTable {
    param(
        [Parameter(Mandatory)][Collections.Specialized.OrderedDictionary]$Columns,
        [object[]]$Rows = @()
    )
    $table = [Data.DataTable]::new()
    foreach ($name in $Columns.Keys) {
        [void]$table.Columns.Add($name, $Columns[$name])
    }
    foreach ($row in $Rows) {
        $dataRow = $table.NewRow()
        foreach ($name in $Columns.Keys) {
            $dataRow[$name] = $row.$name
        }
        $table.Rows.Add($dataRow)
    }
    return , $table
}

function global:Get-HarnessSqlKind {
    param([string]$Sql)
    # Ordered: the cleanup DROP batch also reads sys.database_recovery_status.
    $kinds = [ordered]@{
        DropDatabase = "N'DROP DATABASE '"
        DropLogin = "N'DROP LOGIN '"
        CreateDatabase = "N'CREATE DATABASE '"
        Preflight = ') LoginCount,'
        InitializeMarkers = 'CREATE SCHEMA dh AUTHORIZATION dbo'
        DatabaseIdentity = 'sys.database_recovery_status r ON'
        ReadMarkers = "name IN (N'Dawnholder.DatabaseTool', N'Dawnholder.D1bGoal')"
        ReadSchemaVersion = 'SELECT Version,Name,Checksum FROM dh.SchemaVersion ORDER BY Version'
        SessionId = 'SELECT @@SPID'
        ActiveSessions = 'FROM sys.dm_exec_sessions s WHERE'
        BindingMismatch = "IF OBJECT_ID(N'dh.CharacterAuthority', N'U') IS NOT NULL"
        BindingCount = 'SELECT COUNT(*) FROM dh.CharacterAuthority'
        UserTriggers = 'sys.triggers WHERE is_ms_shipped=0'
        LedgerCount = "IF OBJECT_ID(N'dh.CharacterOperation',N'U') IS NULL"
        LoginSid = 'FROM sys.server_principals WHERE name=@name'
    }
    foreach ($kind in $kinds.Keys) {
        if ($Sql.Contains($kinds[$kind])) {
            return $kind
        }
    }
    return 'Unexpected'
}

function global:Read-HarnessApprovalPlan {
    param([string]$ApprovalPlanPath, [string]$ExpectedApprovalPlanHash)
    Write-HarnessCall -Name 'ReadApprovalPlan' -Detail $ApprovalPlanPath
    if ($ApprovalPlanPath -cne $global:HarnessContract.ApprovalPlanPath -or
        $ExpectedApprovalPlanHash -cne $global:HarnessContract.ApprovalPlanHash) {
        throw 'Offline harness: the entry point did not pass the reviewed plan path and hash through.'
    }
    return $global:HarnessContract.PSObject.Copy()
}

function global:Assert-HarnessExecutor {
    param([switch]$Administrator, $Contract)
    # Only the Windows token/machine comparison is replaced; the product approval check still runs here.
    Write-HarnessCall -Name 'Executor' -Detail ('Administrator=' + [bool]$Administrator)
    Assert-TestEnvironmentExecutionApproval -Contract $Contract
}

function global:Assert-HarnessAccountAbsent {
    param($Contract)
    Write-HarnessCall -Name 'AccountAbsent' -Detail $Contract.RecoveryLocalName
    if ($global:HarnessBehavior.AccountOccupied) {
        throw 'Test environment Windows account name occupied; no adoption.'
    }
}

function global:Get-HarnessLocalUser {
    [CmdletBinding()]
    param([string]$Name, $SID)
    Write-HarnessCall -Name 'GetLocalUser' -Detail $Name
    $users = @($global:HarnessBehavior.LocalUsers | Where-Object Name -CEQ $Name)
    if ($users.Count -eq 1) {
        return [pscustomobject]@{
            Name = $Name
            SID = [Security.Principal.SecurityIdentifier]::new($users[0].Sid)
        }
    }
    $missing = [InvalidOperationException]::new("Offline harness: no fixture local user $Name.")
    throw ([Management.Automation.ErrorRecord]::new(
            $missing,
            'UserNotFound',
            [Management.Automation.ErrorCategory]::ObjectNotFound,
            $Name))
}

function global:Remove-HarnessLocalUser {
    [CmdletBinding()]
    param($SID)
    Write-HarnessCall -Name 'RemoveLocalUser' -Detail ([string]$SID.Value)
}

function global:Assert-HarnessSecretFile {
    param([string]$Path, [string]$ExpectedHash, $Manifest, $Contract)
    # Stands in for the ACL/owner/hash inspection of a credential file; it reads neither ACL nor content.
    Write-HarnessCall -Name 'SecretFile' -Detail $Path
    Assert-HarnessContained -Path $Path
}

function global:Open-HarnessDatabase {
    param($Manifest, [string]$Database, [switch]$Master, $Contract)
    $catalog = $(if ($Master) { 'master' } else { $Database })
    Write-HarnessCall -Name 'Open' -Detail $catalog
    # Returned unopened. No path under test opens it; an accidental Open could only reach a nonexistent
    # local shared-memory instance.
    $builder = [Data.SqlClient.SqlConnectionStringBuilder]::new()
    $builder['Data Source'] = 'lpc:.\OFFLINESTUB'
    $builder['Initial Catalog'] = $catalog
    $builder['Pooling'] = $false
    $builder['Connect Timeout'] = 1
    return [Data.SqlClient.SqlConnection]::new($builder.ConnectionString)
}

function global:Invoke-HarnessMigrations {
    param($Connection, $Transaction = $null, [string]$Phase = 'Complete', $Contract = $null)
    $approved = $null -ne $Contract -and $Contract.ExecutionApproved -eq $true
    $detail = 'Approved=' + $approved + ';Database=' + $Connection.Database
    Write-HarnessCall -Name ('Migrations.' + $Phase) -Detail $detail
    'Offline harness recorded the migration request.'
}

function global:Invoke-HarnessSql {
    param(
        $Connection,
        [string]$Sql,
        [hashtable]$Parameters = @{},
        $Transaction = $null,
        [string]$Result = 'Scalar'
    )
    $kind = Get-HarnessSqlKind -Sql $Sql
    Write-HarnessCall -Name ('Sql.' + $kind) -Detail $Connection.Database
    if ($kind -ceq 'Unexpected') {
        throw 'Offline harness: unexpected SQL reached the stub.'
    }
    $behavior = $global:HarnessBehavior
    if ($behavior.PendingAt -ceq $kind) {
        # Leaves what an interrupted journal write leaves behind, so the next product journal write must fail.
        $pendingPath = $global:HarnessContract.ManifestPath + '.pending'
        Assert-HarnessContained -Path $pendingPath
        if (-not [IO.File]::Exists($pendingPath)) {
            [IO.File]::WriteAllText($pendingPath, 'offline harness interrupted journal write')
        }
    }
    if ($behavior.FailSql -ceq $kind) {
        # By default the safe shape of the product wrapper: provider text suppressed, number kept in Data. A scenario
        # may instead inject unsuppressed provider-like text, an inner exception or a non-numeric code.
        $message = 'Offline harness injected SQL failure (provider number 51199).'
        if ($behavior.FailMessage) {
            $message = [string]$behavior.FailMessage
        }
        $inner = $null
        if ($behavior.FailInnerMessage) {
            $inner = [Exception]::new([string]$behavior.FailInnerMessage)
        }
        $failure = [InvalidOperationException]::new($message, $inner)
        $failure.Data['DatabaseSqlNumber'] = $behavior.FailSqlNumber
        throw $failure
    }
    switch ($kind) {
        'Preflight' {
            $columns = [ordered]@{
                DatabaseCount = [int]
                LoginCount = [int]
                ProductVersion = [string]
                ServerCollation = [string]
                OriginalLogin = [string]
            }
            $row = @{
                DatabaseCount = [int]$behavior.PreflightDatabaseCount
                LoginCount = [int]$behavior.PreflightLoginCount
                ProductVersion = '16.0.1000.6'
                ServerCollation = 'Latin1_General_CI_AS'
                OriginalLogin = 'FIXTUREHOST\executor'
            }
            $table = New-HarnessTable -Columns $columns -Rows @($row)
            return , $table
        }
        'DatabaseIdentity' {
            $columns = [ordered]@{
                DatabaseId = [int]
                CreationTime = [string]
                OwnerSid = [string]
                DatabaseGuid = [string]
                Collation = [string]
                Rcsi = [bool]
                State = [string]
            }
            $row = @{
                DatabaseId = 7
                CreationTime = '2026-10-04T08:30:00.123'
                OwnerSid = '0x010500000000000515000000010000000200000003000000E9030000'
                DatabaseGuid = $global:HarnessScenarioGuid
                Collation = 'Latin1_General_CI_AS'
                Rcsi = $false
                State = 'ONLINE'
            }
            $table = New-HarnessTable -Columns $columns -Rows @($row)
            return , $table
        }
        'ReadMarkers' {
            $columns = [ordered]@{
                name = [string]
                Value = [string]
            }
            $rows = @(
                @{ name = 'Dawnholder.DatabaseTool'; Value = 'development-v1' },
                @{ name = 'Dawnholder.D1bGoal'; Value = $global:HarnessContract.GoalMarker }
            )
            $table = New-HarnessTable -Columns $columns -Rows $rows
            return , $table
        }
        'ReadSchemaVersion' {
            $columns = [ordered]@{
                Version = [int]
                Name = [string]
                Checksum = [string]
            }
            $table = New-HarnessTable -Columns $columns -Rows @($behavior.SchemaRows)
            return , $table
        }
        'SessionId' {
            return 61
        }
        'LoginSid' {
            return $null
        }
        { $_ -in @('ActiveSessions', 'BindingMismatch', 'BindingCount', 'UserTriggers', 'LedgerCount') } {
            return 0
        }
        default {
            return -1
        }
    }
}

function global:Stop-HarnessBoundary {
    # Fail-closed stand-in for every boundary the scenarios must not reach.
    Write-HarnessCall -Name ('Blocked.' + $MyInvocation.InvocationName)
    throw ('Offline harness blocked ' + $MyInvocation.InvocationName + '; it must not run.')
}

$global:HarnessScenarioGuid = $scenario.DatabaseGuid
$shadow = [ordered]@{
    'Assert-TestEnvironmentExecutor' = 'Assert-HarnessExecutor'
    'Assert-TestEnvironmentLocalAccountAbsent' = 'Assert-HarnessAccountAbsent'
    'Get-LocalUser' = 'Get-HarnessLocalUser'
    'Remove-LocalUser' = 'Remove-HarnessLocalUser'
    'Open-TestEnvironmentDatabase' = 'Open-HarnessDatabase'
    'Invoke-DatabaseSql' = 'Invoke-HarnessSql'
    'Assert-TestEnvironmentSecretFile' = 'Stop-HarnessBoundary'
}
if (-not $request.RealReader) {
    $shadow['Read-TestEnvironmentApprovalPlan'] = 'Read-HarnessApprovalPlan'
}
if ($request.Behavior.StubMigrations) {
    $shadow['Invoke-Migrations'] = 'Invoke-HarnessMigrations'
}
if ($request.Behavior.SecretFilesVerified) {
    $shadow['Assert-TestEnvironmentSecretFile'] = 'Assert-HarnessSecretFile'
}
$blocked = @(
    'Open-LocalDatabase',
    'Invoke-DbScalar',
    'Invoke-DbNonQuery',
    'New-LocalUser',
    'Get-LocalGroupMember',
    'Set-TestEnvironmentDirectoryAcl',
    'New-TestEnvironmentOwnedFile',
    'Assert-TestEnvironmentDirectoryAcl',
    'New-TestEnvironmentChildIdentity',
    'Get-Acl',
    'Set-Acl',
    'Start-Process'
)
foreach ($name in $blocked) {
    $shadow[$name] = 'Stop-HarnessBoundary'
}
foreach ($name in $shadow.Keys) {
    Set-Alias -Scope Global -Name $name -Value $shadow[$name]
}

# Check the shadowing with every product definition loaded, exactly as the entry points will resolve it.
$resolved = @(& {
        . (Join-Path $toolRoot 'Database.Common.ps1')
        foreach ($name in $shadow.Keys) {
            $command = Get-Command -Name $name -ErrorAction SilentlyContinue
            $isAlias = $null -ne $command -and $command.CommandType -eq 'Alias'
            [pscustomobject]@{
                Name = $name
                CommandType = $(if ($null -eq $command) { 'Missing' } else { [string]$command.CommandType })
                Target = $(if ($isAlias) { $command.ResolvedCommandName } else { '' })
            }
        }
    })
$boundaryJson = ConvertTo-Json -InputObject $resolved -Depth 3
[IO.File]::WriteAllText((Join-Path $ScenarioRoot ($RunName + '.boundary.json')), $boundaryJson)
if (@($resolved | Where-Object { $_.CommandType -cne 'Alias' -or $_.Target -cne $shadow[$_.Name] }).Count) {
    exit 3
}

$arguments = @{}
foreach ($property in $request.Arguments.PSObject.Properties) {
    $arguments[$property.Name] = [string]$property.Value
}
$paths = @(
    $contract.ManifestPath,
    $contract.SettlementPath,
    $contract.PrivateDirectory,
    $contract.IdentityDirectory,
    $contract.IdentityPath,
    $contract.RuntimeCredentialPath,
    $contract.RecoveryCredentialPath,
    $scenario.PlanPath
)
foreach ($key in @('ManifestPath', 'SettlementPath', 'ApprovalPlanPath')) {
    if ($arguments.ContainsKey($key)) {
        $paths += $arguments[$key]
    }
}
try {
    foreach ($path in $paths) {
        Assert-HarnessContained -Path $path
    }
}
catch {
    exit 4
}

$entries = @{
    New = 'test-environment/New-TestDatabase.ps1'
    Remove = 'test-environment/Remove-TestEnvironment.ps1'
}
$output = @()
$message = $null
try {
    $output = @(& (Join-Path $toolRoot $entries[$request.Entry]) @arguments | ForEach-Object { [string]$_ })
}
catch {
    $message = $_.Exception.Message
}
$outcome = [pscustomobject]@{
    Threw = $null -ne $message
    Message = [string]$message
    Output = $output
}
$outcomeJson = ConvertTo-Json -InputObject $outcome -Depth 4
[IO.File]::WriteAllText((Join-Path $ScenarioRoot ($RunName + '.outcome.json')), $outcomeJson)
exit 0
'@
$harnessPath = Join-Path $script:SuiteRoot 'lifecycle-harness.ps1'
Write-FixtureText -Path $harnessPath -Text $harnessSource

function New-DraftPlanObject {
    param([Parameter(Mandatory)][string]$Root)
    # Same fixture shape as EnvironmentGuards; every lifecycle path stays below this scenario root.
    return [pscustomobject][ordered]@{
        PlanVersion = 1
        SchemaVersion = 1
        ExecutionApproved = $false
        Goal = 'offline-fixture'
        GoalMarker = 'offline-fixture-marker'
        G0 = 'fixture-g0'
        G1 = 'fixture-g1'
        G2 = ''
        Machine = 'FIXTUREHOST'
        Instance = '.\FIXTURE'
        InstanceName = 'FIXTURE'
        Endpoint = 'tcp:127.0.0.1,14330'
        Database = $database
        SlotId = 1
        AccountId = '11111111-1111-1111-1111-111111111111'
        CharacterId = '22222222-2222-2222-2222-222222222222'
        RuntimeLogin = 'dh_fixture_runtime'
        RecoveryPrincipal = 'FIXTUREHOST\dhrecovery'
        RecoveryLocalName = 'dhrecovery'
        ExecutorSid = $executorSid
        Encrypt = $true
        TrustServerCertificate = $true
        ManifestPath = Join-Path $Root 'lifecycle\manifest.json'
        SettlementPath = Join-Path $Root 'lifecycle\settlement.json'
        PrivateDirectory = Join-Path $Root 'private'
        IdentityDirectory = Join-Path $Root 'identity'
        IdentityPath = Join-Path $Root 'identity\identity.json'
        RuntimeCredentialPath = Join-Path $Root 'private\runtime.cred'
        RecoveryCredentialPath = Join-Path $Root 'private\recovery.cred'
    }
}

function New-LifecycleScenario {
    param([Parameter(Mandatory)][string]$Name)
    $root = Join-Path $script:SuiteRoot $Name
    [void][IO.Directory]::CreateDirectory((Join-Path $root 'lifecycle'))
    $plan = New-DraftPlanObject -Root $root
    $planPath = Join-Path $root 'reviewed-plan.json'
    $bytes = (New-Object Text.UTF8Encoding($false)).GetBytes(($plan | ConvertTo-Json -Depth 5))
    [IO.File]::WriteAllBytes($planPath, $bytes)
    $scenario = [pscustomobject]@{
        Name = $Name
        Root = $root
        PlanPath = $planPath
        PlanHash = Get-Sha256Hex -Bytes $bytes
        ManifestPath = $plan.ManifestPath
        SettlementPath = $plan.SettlementPath
        GoalMarker = $plan.GoalMarker
        RecoveryLocalName = $plan.RecoveryLocalName
        RuntimeCredentialPath = $plan.RuntimeCredentialPath
        RecoveryCredentialPath = $plan.RecoveryCredentialPath
        RunCount = 0
    }
    $definition = [pscustomobject]@{
        ToolRoot = $script:ToolRoot
        PlanPath = $planPath
        PlanHash = $scenario.PlanHash
        DatabaseGuid = $fixtureDatabaseGuid
    }
    Write-FixtureText -Path (Join-Path $root 'scenario.json') -Text (ConvertTo-Json -InputObject $definition)
    return $scenario
}

function Read-LifecycleCalls {
    param([Parameter(Mandatory)]$Scenario, [Parameter(Mandatory)][string]$RunName)
    $path = Join-Path $Scenario.Root 'calls.jsonl'
    if (-not [IO.File]::Exists($path)) {
        return @()
    }
    $calls = @([IO.File]::ReadAllLines($path) | Where-Object { $_ } | ForEach-Object { $_ | ConvertFrom-Json })
    return @($calls | Where-Object Run -CEQ $RunName)
}

function Invoke-LifecycleRun {
    param(
        [Parameter(Mandatory)]$Scenario,
        [ValidateSet('New', 'Remove')][string]$Entry = 'New',
        [hashtable]$Arguments = @{},
        [hashtable]$Behavior = @{},
        [switch]$RealReader
    )
    $Scenario.RunCount++
    $name = 'run{0:D2}' -f $Scenario.RunCount
    $entryArguments = [ordered]@{
        ApprovalPlanPath = $Scenario.PlanPath
        ExpectedApprovalPlanHash = $Scenario.PlanHash
        Database = $database
        ManifestPath = $Scenario.ManifestPath
    }
    foreach ($key in $Arguments.Keys) {
        $entryArguments[$key] = $Arguments[$key]
    }
    $effective = [ordered]@{
        PreflightDatabaseCount = 0
        PreflightLoginCount = 0
        AccountOccupied = $false
        FailSql = ''
        FailMessage = ''
        FailInnerMessage = ''
        FailSqlNumber = 51199
        PendingAt = ''
        StubMigrations = $false
        SecretFilesVerified = $false
        SchemaRows = @()
        LocalUsers = @()
    }
    foreach ($key in $Behavior.Keys) {
        $effective[$key] = $Behavior[$key]
    }
    $request = [pscustomobject]@{
        Entry = $Entry
        RealReader = [bool]$RealReader
        Arguments = [pscustomobject]$entryArguments
        Behavior = [pscustomobject]$effective
    }
    $requestPath = Join-Path $Scenario.Root ($name + '.request.json')
    Write-FixtureText -Path $requestPath -Text (ConvertTo-Json -InputObject $request -Depth 6)
    $process = Invoke-PowerShellFile -File $harnessPath -Arguments @('-ScenarioRoot', $Scenario.Root, '-RunName', $name)
    $outcomePath = Join-Path $Scenario.Root ($name + '.outcome.json')
    $outcome = $null
    if ([IO.File]::Exists($outcomePath)) {
        $outcome = Read-FixtureText -Path $outcomePath | ConvertFrom-Json
    }
    $run = [pscustomobject]@{
        Scenario = $Scenario.Name
        Name = $name
        HarnessExit = $process.ExitCode
        HarnessError = $process.StdErr.Trim()
        Completed = $null -ne $outcome -and $process.ExitCode -eq 0
        Threw = $null -ne $outcome -and $outcome.Threw
        Message = $(if ($null -ne $outcome) { [string]$outcome.Message } else { '' })
        Calls = @(Read-LifecycleCalls -Scenario $Scenario -RunName $name)
    }
    $script:AllRuns.Add($run)
    return $run
}

function Get-CallNames {
    param([Parameter(Mandatory)]$Run)
    return @($Run.Calls | ForEach-Object { $_.Name })
}

function Find-Calls {
    param([Parameter(Mandatory)]$Run, [Parameter(Mandatory)][string]$Pattern)
    return @($Run.Calls | Where-Object { $_.Name -cmatch $Pattern })
}

function Get-JournalAt {
    param([Parameter(Mandatory)]$Run, [Parameter(Mandatory)][string]$Name)
    $call = @($Run.Calls | Where-Object Name -CEQ $Name)
    if ($call.Count -eq 0) {
        return 'not reached'
    }
    return [string]$call[0].Journal
}

function Format-RunDetail {
    param([Parameter(Mandatory)]$Run)
    return ('{0}/{1} exit={2} threw={3} message=<{4}> calls={5} stderr=<{6}>' -f $Run.Scenario, $Run.Name,
        $Run.HarnessExit, $Run.Threw, $Run.Message, ((Get-CallNames -Run $Run) -join '>'), $Run.HarnessError)
}

function Read-LifecycleManifest {
    param([Parameter(Mandatory)]$Scenario)
    if (-not [IO.File]::Exists($Scenario.ManifestPath)) {
        return $null
    }
    return Read-FixtureText -Path $Scenario.ManifestPath | ConvertFrom-Json
}

function Get-FileHashHex {
    param([Parameter(Mandatory)][string]$Path)
    if (-not [IO.File]::Exists($Path)) {
        return 'absent'
    }
    return Get-Sha256Hex -Bytes ([IO.File]::ReadAllBytes($Path))
}

function Get-StepStatus {
    param($Manifest, [Parameter(Mandatory)][string]$Name)
    $step = @($Manifest.Steps | Where-Object Name -CEQ $Name)
    if ($step.Count -ne 1) {
        return 'absent'
    }
    return [string]$step[0].Status
}

function Get-RecordedMigrationRows {
    param([Parameter(Mandatory)][int]$Count)
    # Rows shaped like dh.SchemaVersion; checksums come from the independent TestSupport recomputation.
    $names = @('001_initial.sql', '002_persistence_metadata.sql', '003_module_metadata.sql', '004_module_release.sql')
    return @(for ($index = 0; $index -lt $Count; $index++) {
            $source = Join-Path $script:ToolRoot ('migrations/' + $names[$index])
            [pscustomobject]@{
                Version = $index + 1
                Name = $names[$index]
                Checksum = (Get-ExpectedModuleValues -Path $source).SourceChecksum
            }
        })
}

function Write-CleanupSettlement {
    param([Parameter(Mandatory)]$Scenario)
    # Complete nonsecret settlement with one preserved evidence file beside the manifest.
    $evidencePath = Join-Path $Scenario.Root 'lifecycle\run-evidence.txt'
    Write-FixtureText -Path $evidencePath -Text 'offline fixture evidence'
    $settlement = [pscustomobject]@{
        SchemaVersion = 1
        GoalMarker = $Scenario.GoalMarker
        Database = $database
        DatabaseGuid = $fixtureDatabaseGuid
        ExecutorSid = $executorSid
        RequestsComplete = $true
        ProducersStopped = $true
        OldRequestsCannotArrive = $true
        EvidencePreserved = $true
        Unresolved = @()
        PendingRequests = @()
        HeldOwners = @()
        RemainingTriggers = @()
        Evidence = @([pscustomobject]@{ Path = $evidencePath; Hash = (Get-FileHashHex -Path $evidencePath) })
        Connections = @()
        Requests = @()
        LedgerCount = 0
    }
    Write-FixtureText -Path $Scenario.SettlementPath -Text (ConvertTo-Json -InputObject $settlement -Depth 5)
}

function Get-RemoveArguments {
    param([Parameter(Mandatory)]$Scenario, [Parameter(Mandatory)][string]$Mode, [string]$ManifestHash = '')
    $arguments = @{
        Mode = $Mode
        SettlementPath = $Scenario.SettlementPath
    }
    if ($Mode -ceq 'Execute') {
        $arguments.ConfirmDatabase = $database
        $arguments.ExpectedManifestHash = $(if ($ManifestHash) { $ManifestHash } else {
                Get-FileHashHex -Path $Scenario.ManifestPath
            })
    }
    return $arguments
}

$baselineRows = @(Get-RecordedMigrationRows -Count 1)
$completeRows = @(Get-RecordedMigrationRows -Count 4)
$noConnection = '^(Open|Sql\.)'

function Get-ManifestState {
    param([Parameter(Mandatory)]$Scenario)
    # Flow assertions also require the state their stimulus assumes, so an upstream failure cannot pass them.
    $current = Read-LifecycleManifest -Scenario $Scenario
    if ($null -eq $current) {
        return 'absent'
    }
    return [string]$current.State
}

function Get-ScenarioStepStatus {
    param([Parameter(Mandatory)]$Scenario, [Parameter(Mandatory)][string]$Name)
    $current = Read-LifecycleManifest -Scenario $Scenario
    if ($null -eq $current) {
        return 'absent'
    }
    return Get-StepStatus -Manifest $current -Name $Name
}

function Test-CreatedWithIdentity {
    param([Parameter(Mandatory)]$Scenario)
    $current = Read-LifecycleManifest -Scenario $Scenario
    return $null -ne $current -and $current.State -ceq 'Created' -and $null -ne $current.DatabaseIdentity
}

function New-ApprovedContract {
    param([Parameter(Mandatory)][string]$Root)
    # In memory only, as in EnvironmentGuards: never written as a plan file or passed to an entry point.
    [void][IO.Directory]::CreateDirectory((Join-Path $Root 'lifecycle'))
    $contract = New-DraftPlanObject -Root $Root
    $contract.ExecutionApproved = $true
    $contract.G2 = 'fixture-g2-in-memory'
    $planPath = Join-Path $Root 'reviewed-plan.json'
    $contract | Add-Member -MemberType NoteProperty -Name ApprovalPlanPath -Value $planPath
    $contract | Add-Member -MemberType NoteProperty -Name ApprovalPlanHash -Value ('B' * 64)
    return $contract
}

# ---- A draft plan stops at the approval gate before the journal lock and before any I/O boundary.
$draft = New-LifecycleScenario -Name 'draft-plan'
foreach ($case in @(
        @{ Action = 'Plan' },
        @{ Action = 'Create' },
        @{ Action = 'Install'; Phase = 'Baseline001' }
    )) {
    $run = Invoke-LifecycleRun -Scenario $draft -Arguments $case -RealReader
    Assert-True -Name ("draft plan $($case.Action) stops before the lock file, manifest and every I/O boundary") `
        -Condition ($run.Completed -and $run.Message -cmatch '^Draft plan cannot execute' -and
            -not [IO.File]::Exists($draft.ManifestPath + '.lock') -and -not [IO.File]::Exists($draft.ManifestPath) -and
            @(Find-Calls -Run $run -Pattern '^(Open|Sql\.|AccountAbsent|GetLocalUser|Migrations\.)').Count -eq 0) `
        -Detail (Format-RunDetail -Run $run)
}
$boundaryText = Read-FixtureText -Path (Join-Path $draft.Root 'run01.boundary.json')
$boundary = @($boundaryText | ConvertFrom-Json | ForEach-Object { $_ })
Assert-True -Name 'harness verified every SQL/identity/account/ACL/credential/process boundary as shadowed' -Condition (
    $boundary.Count -ge 18 -and @($boundary | Where-Object CommandType -CNE 'Alias').Count -eq 0) `
    -Detail ((@($boundary | ForEach-Object { $_.Name + '->' + $_.Target })) -join ', ')

# ---- Plan -> Create -> Baseline001 -> Complete, each one-time and in order.
$order = New-LifecycleScenario -Name 'order'
$plan = Invoke-LifecycleRun -Scenario $order -Arguments @{ Action = 'Plan' }
$manifest = Read-LifecycleManifest -Scenario $order
Assert-True -Name 'Plan journals a Planned manifest with no connection, SQL or account call' -Condition (
    $plan.Completed -and -not $plan.Threw -and $null -ne $manifest -and $manifest.State -ceq 'Planned' -and
    @($manifest.Steps).Count -eq 0 -and $manifest.ApprovalPlanHash -ceq $order.PlanHash -and
    @(Find-Calls -Run $plan -Pattern '^(Open|Sql\.|AccountAbsent|GetLocalUser)').Count -eq 0) `
    -Detail (Format-RunDetail -Run $plan)

$before = Get-ManifestState -Scenario $order
$early = Invoke-LifecycleRun -Scenario $order -Arguments @{ Action = 'Install'; Phase = 'Baseline001' } `
    -Behavior @{ StubMigrations = $true; SchemaRows = $baselineRows }
Assert-True -Name 'Install before Create stops without journaling a step or reaching the migration runner' -Condition (
    $before -ceq 'Planned' -and $early.Completed -and $early.Threw -and
    @((Read-LifecycleManifest -Scenario $order).Steps).Count -eq 0 -and
    @(Find-Calls -Run $early -Pattern '^(Migrations\.|Sql\.(CreateDatabase|InitializeMarkers))').Count -eq 0) `
    -Detail ('before=' + $before + '; ' + (Format-RunDetail -Run $early))

$before = Get-ManifestState -Scenario $order
$create = Invoke-LifecycleRun -Scenario $order -Arguments @{ Action = 'Create' }
$manifest = Read-LifecycleManifest -Scenario $order
$names = @(Get-CallNames -Run $create)
$createAt = [Array]::IndexOf($names, 'Sql.CreateDatabase')
Assert-True -Name 'executor gate precedes the first connection of Create' -Condition (
    [Array]::IndexOf($names, 'Executor') -ge 0 -and
    [Array]::IndexOf($names, 'Executor') -lt [Array]::IndexOf($names, 'Open')) -Detail (Format-RunDetail -Run $create)
Assert-True -Name 'Create proves the exact Windows account and SQL names absent before CREATE DATABASE' -Condition (
    $createAt -gt 0 -and [Array]::IndexOf($names, 'AccountAbsent') -in 0..($createAt - 1) -and
    [Array]::IndexOf($names, 'Sql.Preflight') -in 0..($createAt - 1)) -Detail (Format-RunDetail -Run $create)
$journal = Get-JournalAt -Run $create -Name 'Sql.CreateDatabase'
Assert-True -Name 'CREATE DATABASE is issued only after its one-time step is journaled Pending' -Condition (
    $journal -cmatch '^State=Planned;' -and $journal -cmatch '(^|[;,])CreateDatabase:Pending$') -Detail $journal
$journal = Get-JournalAt -Run $create -Name 'Sql.InitializeMarkers'
Assert-True -Name 'marker bootstrap runs only after CreateDatabase is Done with an identity and its own step Pending' `
    -Condition ($journal -cmatch 'CreateDatabase:Done,InitializeDatabaseMarkers:Pending$') -Detail $journal
Assert-True -Name 'Create records the exact database identity and leaves state Created with both steps Done' `
    -Condition ($before -ceq 'Planned' -and $create.Completed -and -not $create.Threw -and
        $manifest.State -ceq 'Created' -and $null -ne $manifest.DatabaseIdentity -and
        [string]$manifest.DatabaseIdentity.DatabaseGuid -ceq $fixtureDatabaseGuid -and
        (Get-StepStatus -Manifest $manifest -Name 'CreateDatabase') -ceq 'Done' -and
        (Get-StepStatus -Manifest $manifest -Name 'InitializeDatabaseMarkers') -ceq 'Done') `
    -Detail (Format-RunDetail -Run $create)

$before = Get-ManifestState -Scenario $order
$skip = Invoke-LifecycleRun -Scenario $order -Arguments @{ Action = 'Install'; Phase = 'Complete' } `
    -Behavior @{ StubMigrations = $true; SchemaRows = $completeRows }
Assert-True -Name 'Complete before Baseline001 stops without journaling or migrating' -Condition (
    $before -ceq 'Created' -and $skip.Completed -and $skip.Threw -and
    @((Read-LifecycleManifest -Scenario $order).Steps).Count -eq 2 -and
    @(Find-Calls -Run $skip -Pattern '^Migrations\.').Count -eq 0) `
    -Detail ('before=' + $before + '; ' + (Format-RunDetail -Run $skip))

$before = Get-ManifestState -Scenario $order
$baseline = Invoke-LifecycleRun -Scenario $order -Arguments @{ Action = 'Install'; Phase = 'Baseline001' } `
    -Behavior @{ StubMigrations = $true; SchemaRows = $baselineRows }
$manifest = Read-LifecycleManifest -Scenario $order
$migrations = @(Find-Calls -Run $baseline -Pattern '^Migrations\.')
Assert-True -Name 'Baseline001 reaches the runner once, for phase Baseline001, after journaling its step Pending' `
    -Condition ($migrations.Count -eq 1 -and $migrations[0].Name -ceq 'Migrations.Baseline001' -and
        [string]$migrations[0].Journal -cmatch '^State=Created;.*InstallBaseline001:Pending$') `
    -Detail (Format-RunDetail -Run $baseline)
Assert-True -Name 'Baseline001 leaves state Baseline001 with exactly the 001 row recorded' -Condition (
    $before -ceq 'Created' -and -not $baseline.Threw -and $manifest.State -ceq 'Baseline001' -and
    @($manifest.MigrationManifest).Count -eq 1 -and @($manifest.MigrationManifest)[0].Name -ceq '001_initial.sql' -and
    (Get-StepStatus -Manifest $manifest -Name 'InstallBaseline001') -ceq 'Done') `
    -Detail ('before=' + $before + '; ' + (Format-RunDetail -Run $baseline))

$before = Get-ManifestState -Scenario $order
$again = Invoke-LifecycleRun -Scenario $order -Arguments @{ Action = 'Install'; Phase = 'Baseline001' } `
    -Behavior @{ StubMigrations = $true; SchemaRows = $baselineRows }
Assert-True -Name 'a second Baseline001 install is refused without reaching the runner' -Condition (
    $before -ceq 'Baseline001' -and $again.Completed -and $again.Threw -and
    @(Find-Calls -Run $again -Pattern '^Migrations\.').Count -eq 0 -and
    (Get-ManifestState -Scenario $order) -ceq 'Baseline001') `
    -Detail ('before=' + $before + '; ' + (Format-RunDetail -Run $again))

$before = Get-ManifestState -Scenario $order
$complete = Invoke-LifecycleRun -Scenario $order -Arguments @{ Action = 'Install'; Phase = 'Complete' } `
    -Behavior @{ StubMigrations = $true; SchemaRows = $completeRows }
$manifest = Read-LifecycleManifest -Scenario $order
$migrations = @(Find-Calls -Run $complete -Pattern '^Migrations\.')
Assert-True -Name 'Complete reaches the runner once with the approved contract and exact database' -Condition (
    $migrations.Count -eq 1 -and $migrations[0].Name -ceq 'Migrations.Complete' -and
    [string]$migrations[0].Detail -ceq ('Approved=True;Database=' + $database) -and
    [string]$migrations[0].Journal -cmatch 'InstallComplete:Pending$') -Detail (Format-RunDetail -Run $complete)
Assert-True -Name 'Complete leaves state Installed with the four reviewed migration rows' -Condition (
    $before -ceq 'Baseline001' -and -not $complete.Threw -and $manifest.State -ceq 'Installed' -and
    @($manifest.MigrationManifest).Count -eq 4 -and
    ((@($manifest.MigrationManifest) | ForEach-Object { $_.Name }) -join '|') -ceq
    '001_initial.sql|002_persistence_metadata.sql|003_module_metadata.sql|004_module_release.sql') `
    -Detail ('before=' + $before + '; ' + (Format-RunDetail -Run $complete))

$installedBefore = Get-ManifestState -Scenario $order
$installedHash = Get-FileHashHex -Path $order.ManifestPath
$completeAgain = @{ Action = 'Install'; Phase = 'Complete' }
foreach ($case in @(
        @{ Name = 'Complete again'; Arguments = $completeAgain; Pattern = '^Migrations\.' },
        @{ Name = 'Create again'; Arguments = @{ Action = 'Create' }; Pattern = '^Sql\.CreateDatabase$' },
        @{ Name = 'Plan again'; Arguments = @{ Action = 'Plan' }; Pattern = $noConnection }
    )) {
    $run = Invoke-LifecycleRun -Scenario $order -Arguments $case.Arguments `
        -Behavior @{ StubMigrations = $true; SchemaRows = $completeRows }
    Assert-True -Name ("$($case.Name) after Installed is refused without its side effect or a journal change") `
        -Condition ($installedBefore -ceq 'Installed' -and $run.Completed -and $run.Threw -and
            @(Find-Calls -Run $run -Pattern $case.Pattern).Count -eq 0 -and
            (Get-FileHashHex -Path $order.ManifestPath) -ceq $installedHash) `
        -Detail ('before=' + $installedBefore + '; ' + (Format-RunDetail -Run $run))
}

# ---- An exact occupied name stops Create before CREATE DATABASE and without adoption.
$occupied = New-LifecycleScenario -Name 'occupied-name'
$null = Invoke-LifecycleRun -Scenario $occupied -Arguments @{ Action = 'Plan' }
$takenDatabase = $null
foreach ($case in @(
        @{ Name = 'database name'; Behavior = @{ PreflightDatabaseCount = 1 } },
        @{ Name = 'SQL login name'; Behavior = @{ PreflightLoginCount = 1 } },
        @{ Name = 'Windows account name'; Behavior = @{ AccountOccupied = $true } }
    )) {
    $before = Get-ManifestState -Scenario $occupied
    $run = Invoke-LifecycleRun -Scenario $occupied -Arguments @{ Action = 'Create' } -Behavior $case.Behavior
    if ($null -eq $takenDatabase) {
        $takenDatabase = $run
    }
    $manifest = Read-LifecycleManifest -Scenario $occupied
    Assert-True -Name ("occupied exact $($case.Name) stops Create without CREATE DATABASE or adoption") -Condition (
        $before -ceq 'Planned' -and $run.Completed -and $run.Threw -and
        @(Find-Calls -Run $run -Pattern '^Sql\.CreateDatabase$').Count -eq 0 -and
        $manifest.State -ceq 'Planned' -and $null -eq $manifest.DatabaseIdentity -and @($manifest.Steps).Count -eq 0) `
        -Detail ('before=' + $before + '; ' + (Format-RunDetail -Run $run))
}
# G1 stops on an existing exact name and the execution plan has an unexpected DB/principal reported; the executor
# has only this message to report, because the occupied check runs before any journal step.
Assert-True -Name 'an occupied exact database name is reported as occupied to the executor' -Condition (
    $takenDatabase.Message -cmatch 'occupied') -Detail (Format-RunDetail -Run $takenDatabase)

# ---- A failed CREATE DATABASE is journaled and blocks every retry, install and tool cleanup.
$failedCreate = New-LifecycleScenario -Name 'create-failure'
$null = Invoke-LifecycleRun -Scenario $failedCreate -Arguments @{ Action = 'Plan' }
$before = Get-ManifestState -Scenario $failedCreate
$failure = Invoke-LifecycleRun -Scenario $failedCreate -Arguments @{ Action = 'Create' } `
    -Behavior @{ FailSql = 'CreateDatabase' }
$manifest = Read-LifecycleManifest -Scenario $failedCreate
$step = @($manifest.Steps | Where-Object Name -CEQ 'CreateDatabase')
$failedJournaled = $step.Count -eq 1 -and $step[0].Status -ceq 'Failed'
Assert-True -Name 'failed CREATE DATABASE journals CreateDatabase Failed with the safe failure code and no identity' `
    -Condition ($before -ceq 'Planned' -and $failure.Completed -and
        $failure.Message -cmatch 'preserve manifest and all resources' -and $failedJournaled -and
        [int]$step[0].Failure.SqlNumber -eq 51199 -and $manifest.State -ceq 'Planned' -and
        $null -eq $manifest.DatabaseIdentity -and
        @(Find-Calls -Run $failure -Pattern '^Sql\.InitializeMarkers$').Count -eq 0) `
    -Detail (Format-RunDetail -Run $failure)
$failedHash = Get-FileHashHex -Path $failedCreate.ManifestPath
foreach ($case in @(
        @{ Name = 'Create retry'; Arguments = @{ Action = 'Create' } },
        @{ Name = 'Install Baseline001'; Arguments = @{ Action = 'Install'; Phase = 'Baseline001' } }
    )) {
    $run = Invoke-LifecycleRun -Scenario $failedCreate -Arguments $case.Arguments
    Assert-True -Name ("$($case.Name) after a failed step is refused before any connection") -Condition (
        $failedJournaled -and $run.Completed -and $run.Threw -and
        @(Find-Calls -Run $run -Pattern $noConnection).Count -eq 0 -and
        (Get-FileHashHex -Path $failedCreate.ManifestPath) -ceq $failedHash) `
        -Detail ('failedJournaled=' + $failedJournaled + '; ' + (Format-RunDetail -Run $run))
}
Write-CleanupSettlement -Scenario $failedCreate
$run = Invoke-LifecycleRun -Scenario $failedCreate -Entry Remove `
    -Arguments (Get-RemoveArguments -Scenario $failedCreate -Mode 'Execute')
Assert-True -Name 'cleanup Execute after an unrecorded database identity drops nothing and changes no journal' `
    -Condition ($failedJournaled -and $run.Completed -and $run.Threw -and
        @(Find-Calls -Run $run -Pattern '^(Open|Sql\.Drop)').Count -eq 0 -and
        (Get-FileHashHex -Path $failedCreate.ManifestPath) -ceq $failedHash) `
    -Detail ('failedJournaled=' + $failedJournaled + '; ' + (Format-RunDetail -Run $run))

# ---- The real installer core and runner stop at the offline boundary; the one-time step stays Failed.
$runner = New-LifecycleScenario -Name 'runner-failure'
$null = Invoke-LifecycleRun -Scenario $runner -Arguments @{ Action = 'Plan' }
$null = Invoke-LifecycleRun -Scenario $runner -Arguments @{ Action = 'Create' }
$before = Get-ManifestState -Scenario $runner
$install = Invoke-LifecycleRun -Scenario $runner -Arguments @{ Action = 'Install'; Phase = 'Baseline001' }
$manifest = Read-LifecycleManifest -Scenario $runner
$step = @($manifest.Steps | Where-Object Name -CEQ 'InstallBaseline001')
$runnerFailed = $step.Count -eq 1 -and $step[0].Status -ceq 'Failed'
Assert-True -Name 'runner failure inside Baseline001 journals the step Failed and keeps state Created without rows' `
    -Condition ($before -ceq 'Created' -and $install.Completed -and $install.Threw -and $runnerFailed -and
        -not [string]::IsNullOrWhiteSpace([string]$step[0].Failure.ErrorType) -and $manifest.State -ceq 'Created' -and
        @($manifest.MigrationManifest).Count -eq 0 -and @(Find-Calls -Run $install -Pattern '^Blocked\.').Count -eq 0) `
    -Detail ('before=' + $before + '; ' + (Format-RunDetail -Run $install) + '; failure=' +
        ($step | ConvertTo-Json -Compress -Depth 4))
$retry = Invoke-LifecycleRun -Scenario $runner -Arguments @{ Action = 'Install'; Phase = 'Baseline001' } `
    -Behavior @{ StubMigrations = $true; SchemaRows = $baselineRows }
Assert-True -Name 'Baseline001 retry after a runner failure is refused before any connection' -Condition (
    $runnerFailed -and $retry.Completed -and $retry.Threw -and
    @(Find-Calls -Run $retry -Pattern $noConnection).Count -eq 0) `
    -Detail ('runnerFailed=' + $runnerFailed + '; ' + (Format-RunDetail -Run $retry))

# ---- An equivalent manifest path accepted by entry validation must not burn the one-time install step.
$pathForm = New-LifecycleScenario -Name 'manifest-path-form'
$null = Invoke-LifecycleRun -Scenario $pathForm -Arguments @{ Action = 'Plan' }
$null = Invoke-LifecycleRun -Scenario $pathForm -Arguments @{ Action = 'Create' }
$slashed = $pathForm.ManifestPath.Replace('\', '/')
Assert-NoThrow -Name 'entry validation accepts the forward-slash form of the exact approved manifest path' -Action {
    Assert-TestEnvironmentPath -Path $slashed -Expected $pathForm.ManifestPath
}
$before = Get-ManifestState -Scenario $pathForm
$slashedInstall = @{
    Action = 'Install'
    Phase = 'Baseline001'
    ManifestPath = $slashed
}
$install = Invoke-LifecycleRun -Scenario $pathForm -Arguments $slashedInstall `
    -Behavior @{ StubMigrations = $true; SchemaRows = $baselineRows }
$status = Get-ScenarioStepStatus -Scenario $pathForm -Name 'InstallBaseline001'
$reached = @(Find-Calls -Run $install -Pattern '^Migrations\.').Count
$refusedEarly = $status -ceq 'absent' -and $reached -eq 0
$installed = $status -ceq 'Done' -and $reached -eq 1
Assert-True -Name 'an accepted equivalent manifest path is refused before journaling or installs normally' `
    -Condition ($before -ceq 'Created' -and $install.Completed -and ($refusedEarly -or $installed)) `
    -Detail ('before=' + $before + '; InstallBaseline001=' + $status + '; runner calls=' + $reached + '; ' +
        (Format-RunDetail -Run $install))

# ---- The installer core, called directly with the lock opened from the path the entry point received.
$coreContract = New-ApprovedContract -Root (Join-Path $script:SuiteRoot 'installer-core')
$coreManifest = New-TestEnvironmentManifest -Contract $coreContract -Database $database
$coreManifest.State = 'Created'
$coreManifest.Steps = @([pscustomobject]@{
        Name = 'InstallBaseline001'
        Status = 'Pending'
        PlannedUtc = [DateTime]::UtcNow.ToString('o')
        Plan = $null
        CompletedUtc = $null
        Identity = $null
        Failure = $null
    })
Write-TestEnvironmentManifest -Contract $coreContract -Manifest $coreManifest

function Get-InstallerCoreMessage {
    param(
        [Parameter(Mandatory)][string]$ManifestPath,
        [string]$LockPath = '',
        [IO.FileAccess]$LockAccess = [IO.FileAccess]::ReadWrite,
        [string]$ConnectionDatabase = ''
    )
    # Opened as Lock-TestEnvironmentManifest opens it; the connection stays unopened like the harness one.
    # The optional values build the refusal counterexamples: another lock file, a read-only lock, another database.
    if (-not $LockPath) {
        $LockPath = $ManifestPath + '.lock'
    }
    if (-not $ConnectionDatabase) {
        $ConnectionDatabase = $database
    }
    $lock = [IO.File]::Open($LockPath, [IO.FileMode]::OpenOrCreate, $LockAccess, [IO.FileShare]::None)
    $connection = [Data.SqlClient.SqlConnection]::new(
        'Data Source=lpc:.\OFFLINESTUB;Initial Catalog=' + $ConnectionDatabase)
    try {
        return Get-ThrownMessage -Action {
            # Distinct block parameter names: dot-sourcing binds the installer's own parameters in this scope.
            & {
                param($ApprovedContract, $ApprovedDatabase, $CorePath, $CoreLock, $CoreConnection)
                . (Join-Path $script:ToolRoot 'Install-Database.ps1')
                Invoke-TestEnvironmentInstall -Contract $ApprovedContract -Database $ApprovedDatabase `
                    -ManifestPath $CorePath -Phase Baseline001 -Connection $CoreConnection -ManifestLock $CoreLock
            } $coreContract $database $ManifestPath $lock $connection
        }
    }
    finally {
        $lock.Dispose()
        $connection.Dispose()
    }
}
# Accepting the lock lets the core read the journal and reach the marker query, which the offline stub stops.
$reachedMarkers = '^Offline test stub: Invoke-DatabaseSql must not run'
$canonicalMessage = [string](Get-InstallerCoreMessage -ManifestPath $coreContract.ManifestPath)
Assert-True -Name 'installer core accepts the lifecycle lock of the canonical manifest path (control)' -Condition (
    $canonicalMessage -cmatch $reachedMarkers) -Detail $canonicalMessage
$slashedMessage = [string](Get-InstallerCoreMessage -ManifestPath $coreContract.ManifestPath.Replace('\', '/'))
Assert-True -Name 'installer core accepts the lifecycle lock of an equivalent manifest path the entry point accepted' `
    -Condition ($slashedMessage -cmatch $reachedMarkers) -Detail $slashedMessage
# Accepting equivalent path spellings must not accept another lock or connection: these stop at the lock gate.
$refusedAtLockGate = '^Installer core requires the lifecycle-owned manifest lock and exact connection\.$'
$otherLockPath = Join-Path (Split-Path -Parent $coreContract.ManifestPath) 'other-manifest.json.lock'
foreach ($case in @(
        @{ Name = 'a lock held on another file'; Arguments = @{ LockPath = $otherLockPath } },
        @{ Name = 'a read-only handle on the manifest lock file'; Arguments = @{ LockAccess = [IO.FileAccess]::Read } },
        @{ Name = 'a connection to another database'; Arguments = @{ ConnectionDatabase = 'Dawnholder_Dev_Other' } }
    )) {
    $coreArguments = $case.Arguments
    $refusalMessage = [string](Get-InstallerCoreMessage -ManifestPath $coreContract.ManifestPath @coreArguments)
    Assert-True -Name ("installer core refuses $($case.Name) before reading the journal") -Condition (
        $refusalMessage -cmatch $refusedAtLockGate) -Detail $refusalMessage
}

# ---- Cleanup: OnlinePreview changes nothing; Execute needs exact confirmation, reviewed hash and elevation.
$cleanup = New-LifecycleScenario -Name 'cleanup'
$null = Invoke-LifecycleRun -Scenario $cleanup -Arguments @{ Action = 'Plan' }
$null = Invoke-LifecycleRun -Scenario $cleanup -Arguments @{ Action = 'Create' }
$cleanupReady = Test-CreatedWithIdentity -Scenario $cleanup
# Principal fields as Set-TestPrincipals records them before a later login step fails: two credential files
# (placeholders, no secret) and the new Windows account. Cleanup must remove exactly these recorded resources.
[void][IO.Directory]::CreateDirectory((Split-Path -Parent $cleanup.RuntimeCredentialPath))
$manifest = Read-LifecycleManifest -Scenario $cleanup
foreach ($kind in @('Runtime', 'Recovery')) {
    $credentialPath = $cleanup.($kind + 'CredentialPath')
    Write-FixtureText -Path $credentialPath -Text ('offline placeholder, not a credential: ' + $kind)
    $manifest.($kind + 'CredentialHash') = Get-FileHashHex -Path $credentialPath
}
$manifest.WindowsAccountSid = $recoveryAccountSid
Write-FixtureText -Path $cleanup.ManifestPath -Text ($manifest | ConvertTo-Json -Depth 20)
Write-CleanupSettlement -Scenario $cleanup
$cleanupBehavior = @{
    SecretFilesVerified = $true
    LocalUsers = @([pscustomobject]@{ Name = $cleanup.RecoveryLocalName; Sid = $recoveryAccountSid })
}
$reviewedHash = Get-FileHashHex -Path $cleanup.ManifestPath

$preview = Invoke-LifecycleRun -Scenario $cleanup -Entry Remove -Behavior $cleanupBehavior `
    -Arguments (Get-RemoveArguments -Scenario $cleanup -Mode 'OnlinePreview')
$previewElevated = @($preview.Calls | Where-Object { $_.Name -ceq 'Executor' -and $_.Detail -ceq 'Administrator=True' })
Assert-True -Name 'OnlinePreview passes the identity/settlement preflight and changes no resource or journal' `
    -Condition ($cleanupReady -and $preview.Completed -and -not $preview.Threw -and $previewElevated.Count -eq 0 -and
        (Get-FileHashHex -Path $cleanup.ManifestPath) -ceq $reviewedHash -and
        @(Find-Calls -Run $preview -Pattern '^(Sql\.Drop|RemoveLocalUser)').Count -eq 0) `
    -Detail ('cleanupReady=' + $cleanupReady + '; ' + (Format-RunDetail -Run $preview))

$arguments = Get-RemoveArguments -Scenario $cleanup -Mode 'Execute'
$arguments.Remove('ConfirmDatabase')
$run = Invoke-LifecycleRun -Scenario $cleanup -Entry Remove -Arguments $arguments -Behavior $cleanupBehavior
Assert-True -Name 'cleanup Execute without exact database confirmation is refused before any connection' -Condition (
    $run.Completed -and $run.Message -cmatch '^Execute requires an exact database confirmation' -and
    @(Find-Calls -Run $run -Pattern $noConnection).Count -eq 0 -and
    (Get-FileHashHex -Path $cleanup.ManifestPath) -ceq $reviewedHash) -Detail (Format-RunDetail -Run $run)
$run = Invoke-LifecycleRun -Scenario $cleanup -Entry Remove -Behavior $cleanupBehavior `
    -Arguments (Get-RemoveArguments -Scenario $cleanup -Mode 'Execute' -ManifestHash ('A' * 64))
Assert-True -Name 'cleanup Execute with a manifest hash other than the reviewed one is refused before any connection' `
    -Condition ($cleanupReady -and $run.Completed -and $run.Threw -and
        @(Find-Calls -Run $run -Pattern $noConnection).Count -eq 0 -and
        (Get-FileHashHex -Path $cleanup.ManifestPath) -ceq $reviewedHash) `
    -Detail ('cleanupReady=' + $cleanupReady + '; ' + (Format-RunDetail -Run $run))

$execute = Invoke-LifecycleRun -Scenario $cleanup -Entry Remove -Behavior $cleanupBehavior `
    -Arguments (Get-RemoveArguments -Scenario $cleanup -Mode 'Execute')
$names = @(Get-CallNames -Run $execute)
$elevated = @($execute.Calls | Where-Object { $_.Name -ceq 'Executor' -and $_.Detail -ceq 'Administrator=True' })
Assert-True -Name 'cleanup Execute requires the elevated approved executor before its first connection' -Condition (
    $elevated.Count -ge 1 -and [Array]::IndexOf($names, 'Executor') -lt [Array]::IndexOf($names, 'Open')) `
    -Detail (Format-RunDetail -Run $execute)
$journal = Get-JournalAt -Run $execute -Name 'Sql.DropDatabase'
Assert-True -Name 'DROP DATABASE is issued only after CleanupStarted and its Pending cleanup step are journaled' `
    -Condition ($journal -cmatch '^State=CleanupStarted;' -and $journal -cmatch 'Cleanup\.DropDatabase:Pending$') `
    -Detail $journal
$lookups = @(Find-Calls -Run $execute -Pattern '^GetLocalUser$' | ForEach-Object { [string]$_.Detail })
Assert-True -Name 'cleanup looks up the Windows account only by the reviewed plan RecoveryLocalName' -Condition (
    $lookups.Count -ge 2 -and @($lookups | Where-Object { $_ -cne $cleanup.RecoveryLocalName }).Count -eq 0) `
    -Detail ('lookups=' + ($lookups -join ',') + '; ' + (Format-RunDetail -Run $execute))
$manifest = Read-LifecycleManifest -Scenario $cleanup
$removed = @(Find-Calls -Run $execute -Pattern '^RemoveLocalUser$')
Assert-True -Name 'cleanup removes the recorded account by its SID and the recorded credentials, then records Removed' `
    -Condition ($execute.Completed -and -not $execute.Threw -and $removed.Count -eq 1 -and
        [string]$removed[0].Detail -ceq $recoveryAccountSid -and $manifest.State -ceq 'Removed' -and
        $null -ne $manifest.Cleanup -and $manifest.Cleanup.State -ceq 'Done' -and
        -not [IO.File]::Exists($cleanup.RuntimeCredentialPath) -and
        -not [IO.File]::Exists($cleanup.RecoveryCredentialPath)) `
    -Detail ('cleanup=' + ($manifest.Cleanup | ConvertTo-Json -Compress -Depth 5) + '; ' +
        (Format-RunDetail -Run $execute))

# ---- A failed DROP is journaled as a partial cleanup and blocks automatic retry and later lifecycle steps.
$dropFailure = New-LifecycleScenario -Name 'cleanup-drop-failure'
$null = Invoke-LifecycleRun -Scenario $dropFailure -Arguments @{ Action = 'Plan' }
$null = Invoke-LifecycleRun -Scenario $dropFailure -Arguments @{ Action = 'Create' }
$dropReady = Test-CreatedWithIdentity -Scenario $dropFailure
Write-CleanupSettlement -Scenario $dropFailure
$failedDrop = Invoke-LifecycleRun -Scenario $dropFailure -Entry Remove -Behavior @{ FailSql = 'DropDatabase' } `
    -Arguments (Get-RemoveArguments -Scenario $dropFailure -Mode 'Execute')
$manifest = Read-LifecycleManifest -Scenario $dropFailure
$cleanupSteps = @(if ($null -ne $manifest.Cleanup) { $manifest.Cleanup.Steps })
Assert-True -Name 'failed DROP leaves CleanupStarted with cleanup Failed, its step Failed and the safe failure code' `
    -Condition ($dropReady -and $failedDrop.Completed -and
        $failedDrop.Message -cmatch 'partial cleanup is recorded' -and $manifest.State -ceq 'CleanupStarted' -and
        $null -ne $manifest.Cleanup -and
        $manifest.Cleanup.State -ceq 'Failed' -and
        [int]$manifest.Cleanup.Failure.SqlNumber -eq 51199 -and $cleanupSteps.Count -eq 1 -and
        $cleanupSteps[0].Name -ceq 'DropDatabase' -and $cleanupSteps[0].Status -ceq 'Failed') `
    -Detail ('dropReady=' + $dropReady + '; cleanup=' + ($manifest.Cleanup | ConvertTo-Json -Compress -Depth 5) +
        '; ' + (Format-RunDetail -Run $failedDrop))
$cleanupFailed = (Get-ManifestState -Scenario $dropFailure) -ceq 'CleanupStarted'
$startedHash = Get-FileHashHex -Path $dropFailure.ManifestPath
$cleanupRetry = Invoke-LifecycleRun -Scenario $dropFailure -Entry Remove `
    -Arguments (Get-RemoveArguments -Scenario $dropFailure -Mode 'Execute')
Assert-True -Name 'cleanup Execute after a partial cleanup is refused before any connection' -Condition (
    $cleanupFailed -and $cleanupRetry.Completed -and $cleanupRetry.Threw -and
    @(Find-Calls -Run $cleanupRetry -Pattern $noConnection).Count -eq 0 -and
    (Get-FileHashHex -Path $dropFailure.ManifestPath) -ceq $startedHash) `
    -Detail ('cleanupFailed=' + $cleanupFailed + '; ' + (Format-RunDetail -Run $cleanupRetry))
$lateInstall = Invoke-LifecycleRun -Scenario $dropFailure -Arguments @{ Action = 'Install'; Phase = 'Baseline001' } `
    -Behavior @{ StubMigrations = $true; SchemaRows = $baselineRows }
Assert-True -Name 'Install after cleanup started is refused before any connection' -Condition (
    $cleanupFailed -and $lateInstall.Completed -and $lateInstall.Threw -and
    @(Find-Calls -Run $lateInstall -Pattern $noConnection).Count -eq 0) `
    -Detail ('cleanupFailed=' + $cleanupFailed + '; ' + (Format-RunDetail -Run $lateInstall))

# ---- structure: cleanup takes the Windows account name from the reviewed plan, never from a literal.
$removeTokens = $null
$removeErrors = $null
$removePath = Join-Path $script:ToolRoot 'test-environment/Remove-TestEnvironment.ps1'
$removeAst = [Management.Automation.Language.Parser]::ParseFile($removePath, [ref]$removeTokens, [ref]$removeErrors)
$accountLookups = @($removeAst.FindAll({
            param($node)
            $node -is [Management.Automation.Language.CommandAst] -and $node.GetCommandName() -ceq 'Get-LocalUser'
        }, $true))
$literalLookups = @(foreach ($lookup in $accountLookups) {
        $elements = @($lookup.CommandElements)
        for ($index = 1; $index -lt $elements.Count - 1; $index++) {
            $isName = $elements[$index] -is [Management.Automation.Language.CommandParameterAst] -and
                $elements[$index].ParameterName -ceq 'Name'
            if ($isName -and $elements[$index + 1] -is [Management.Automation.Language.StringConstantExpressionAst]) {
                'line ' + $lookup.Extent.StartLineNumber + ': ' + $elements[$index + 1].Value
            }
        }
    })
Assert-True -Name 'structure: cleanup looks up Windows accounts by the reviewed plan value, never a name literal' `
    -Condition ($removeErrors.Count -eq 0 -and $accountLookups.Count -ge 2 -and $literalLookups.Count -eq 0) `
    -Detail ('lookups=' + $accountLookups.Count + '; literals=' + ($literalLookups -join ', '))

# ---- The lifecycle connection settings, built by the product statements themselves without the following Open().
# The harness replaces Open-TestEnvironmentDatabase, so its connection-string construction is checked here:
# the function's own $builder statements are taken from its syntax tree and run against a fresh builder.
$parseTokens = $null
$parseErrors = $null
$commonPath = Join-Path $script:ToolRoot 'test-environment/Environment.Common.ps1'
$commonAst = [Management.Automation.Language.Parser]::ParseFile($commonPath, [ref]$parseTokens, [ref]$parseErrors)
$openAst = $commonAst.Find({
        param($node)
        $node -is [Management.Automation.Language.FunctionDefinitionAst] -and
        $node.Name -ceq 'Open-TestEnvironmentDatabase'
    }, $true)
$builderStatements = @()
if ($null -ne $openAst) {
    $builderStatements = @($openAst.Body.EndBlock.Statements | Where-Object { $_.Extent.Text -cmatch '^\$builder\b' })
}
$builderCreation = '^\$builder = \[Data\.SqlClient\.SqlConnectionStringBuilder\]::new\(\)$'
Assert-True -Name 'the lifecycle connection builder statements are located in Open-TestEnvironmentDatabase' -Condition (
    $parseErrors.Count -eq 0 -and $builderStatements.Count -ge 2 -and
    $builderStatements[0].Extent.Text -cmatch $builderCreation) `
    -Detail ('statements=' + $builderStatements.Count)
# The product statements read the function's own $Manifest, $Master and $Database parameters.
$builderLines = @('param($Manifest, [switch]$Master, [string]$Database)') +
    @($builderStatements | ForEach-Object { $_.Extent.Text }) + @('return , $builder')
$builderBlock = [scriptblock]::Create($builderLines -join "`n")
$builderArguments = @{
    Manifest = [pscustomobject]@{ Instance = '.\FIXTURE' }
    Master = $true
    Database = $database
}
$script:builtSettings = $null
$builderMessage = Get-ThrownMessage -Action { $script:builtSettings = & $builderBlock @builderArguments }
Assert-True -Name 'the product statements build the lifecycle connection settings in this PowerShell host' `
    -Condition ($null -eq $builderMessage -and $null -ne $script:builtSettings) -Detail ([string]$builderMessage)
# G1: exact local shared-memory instance, Windows authentication, mandatory encryption with the fixture-only
# certificate trust; no pooling so the session-owned creation lock ends with the connection.
$expectedSettings = [ordered]@{
    'Data Source' = 'lpc:.\FIXTURE'
    'Initial Catalog' = 'master'
    'Integrated Security' = 'True'
    'Encrypt' = 'True'
    'TrustServerCertificate' = 'True'
    'Pooling' = 'False'
}
$observedSettings = @()
if ($null -ne $script:builtSettings) {
    $parsed = [Data.SqlClient.SqlConnectionStringBuilder]::new([string]$script:builtSettings.ConnectionString)
    $observedSettings = @($expectedSettings.Keys | ForEach-Object { $_ + '=' + [string]$parsed[$_] })
}
$expectedText = @($expectedSettings.Keys | ForEach-Object { $_ + '=' + $expectedSettings[$_] }) -join ';'
Assert-Equal -Name 'the lifecycle connection targets the exact local instance with the reviewed security settings' `
    -Expected $expectedText -Actual ($observedSettings -join ';')

# ---- Journal writes: a later write replaces the manifest; a leftover pending write is preserved, never replaced.
$replaceContract = New-ApprovedContract -Root (Join-Path $script:SuiteRoot 'journal-replace')
$replaceManifest = New-TestEnvironmentManifest -Contract $replaceContract -Database $database
Write-TestEnvironmentManifest -Contract $replaceContract -Manifest $replaceManifest
$replaceManifest.State = 'Created'
Assert-NoThrow -Name 'a second journal write replaces the existing manifest' -Action {
    Write-TestEnvironmentManifest -Contract $replaceContract -Manifest $replaceManifest
}
$replaced = Read-FixtureText -Path $replaceContract.ManifestPath | ConvertFrom-Json
$pendingLeft = [IO.File]::Exists($replaceContract.ManifestPath + '.pending')
Assert-True -Name 'the replaced journal holds the new state and leaves no pending write behind' -Condition (
    $replaced.State -ceq 'Created' -and -not $pendingLeft) `
    -Detail ('state=' + $replaced.State + '; pendingLeft=' + $pendingLeft)

$pendingContract = New-ApprovedContract -Root (Join-Path $script:SuiteRoot 'journal-pending')
$pendingManifest = New-TestEnvironmentManifest -Contract $pendingContract -Database $database
Write-TestEnvironmentManifest -Contract $pendingContract -Manifest $pendingManifest
$writtenHash = Get-FileHashHex -Path $pendingContract.ManifestPath
Write-FixtureText -Path ($pendingContract.ManifestPath + '.pending') -Text 'interrupted write'
$pendingManifest.State = 'Created'
Assert-Throws -Name 'a leftover pending manifest write blocks the next journal write' `
    -Pattern '^Pending manifest remains' `
    -Action { Write-TestEnvironmentManifest -Contract $pendingContract -Manifest $pendingManifest }
Assert-True -Name 'the journal and the leftover pending write both stay unchanged' -Condition (
    (Get-FileHashHex -Path $pendingContract.ManifestPath) -ceq $writtenHash -and
    (Read-FixtureText -Path ($pendingContract.ManifestPath + '.pending')) -ceq 'interrupted write')

# ---- Stop reports. Requirements: G1 and the execution plan (lines 39 and 45) stop on an unexpected DB/principal
# and have it reported with state preserved; main msg_16b3c72e78a6 passes only nonsecret fixed reasons and whether
# the failure journal write actually happened. Each journal claim in an executor message is checked against the
# journal on disk; secrets are fake sentinels. The product reason list is never used as an expected value.
$claimsJournalWritten = '(?i)journal write succeeded|\bis recorded\b'
$claimsJournalWriteFailed = '(?i)journal write failed'
$claimsNoJournalWrite = '(?i)\bno\b[a-z ]*journal write was attempted'
$claimsUnconfirmed = '(?i)\bunconfirmed\b'
$claimsDeletionAttempted = '(?i)(?<!before )resource deletion was attempted'
$claimsStoppedBeforeDeletion = '(?i)before resource deletion'
$unclassifiedReason = '(?i)\bunclassified\b'
$interruptedWrite = 'offline harness interrupted journal write'
$fakeSecret = 'FAKE-SENTINEL-7Q2 Password=fake-not-a-secret'
$fakeInnerSecret = 'FAKE-INNER-SENTINEL-4K8'
$commonFile = [IO.Path]::GetFullPath((Join-Path $script:ToolRoot 'test-environment/Environment.Common.ps1'))

function Get-PendingWriteText {
    param([Parameter(Mandatory)]$Scenario)
    $path = $Scenario.ManifestPath + '.pending'
    if (-not [IO.File]::Exists($path)) {
        return 'absent'
    }
    return Read-FixtureText -Path $path
}

function Get-JournalText {
    param([Parameter(Mandatory)]$Scenario)
    if (-not [IO.File]::Exists($Scenario.ManifestPath)) {
        return ''
    }
    return Read-FixtureText -Path $Scenario.ManifestPath
}

function Get-RunOutcomeText {
    param([Parameter(Mandatory)]$Scenario, [Parameter(Mandatory)]$Run)
    # Everything the entry point returned or threw as the harness captured it, plus the harness error stream.
    $path = Join-Path $Scenario.Root ($Run.Name + '.outcome.json')
    $text = $(if ([IO.File]::Exists($path)) { Read-FixtureText -Path $path } else { '' })
    return $Run.Message + $text + $Run.HarnessError
}

function New-CleanupReadyScenario {
    param([Parameter(Mandatory)][string]$Name)
    # Planned, created with a recorded identity and a complete settlement, as the cleanup scenarios above.
    $scenario = New-LifecycleScenario -Name $Name
    $null = Invoke-LifecycleRun -Scenario $scenario -Arguments @{ Action = 'Plan' }
    $null = Invoke-LifecycleRun -Scenario $scenario -Arguments @{ Action = 'Create' }
    Write-CleanupSettlement -Scenario $scenario
    return $scenario
}

# Create: the reason for an occupied exact name reaches the executor and no journal write is claimed.
$occupiedReport = New-LifecycleScenario -Name 'stop-report-occupied'
$null = Invoke-LifecycleRun -Scenario $occupiedReport -Arguments @{ Action = 'Plan' }
$plannedHash = Get-FileHashHex -Path $occupiedReport.ManifestPath
$run = Invoke-LifecycleRun -Scenario $occupiedReport -Arguments @{ Action = 'Create' } `
    -Behavior @{ PreflightDatabaseCount = 1 }
Assert-True -Name 'an occupied exact name is reported as a classified reason with no journal write claimed' `
    -Condition ($plannedHash -cne 'absent' -and $run.Completed -and $run.Threw -and
        $run.Message -cmatch '(?i)\boccupied\b' -and $run.Message -cnotmatch $unclassifiedReason -and
        $run.Message -cmatch $claimsNoJournalWrite -and $run.Message -cnotmatch $claimsJournalWritten -and
        (Get-FileHashHex -Path $occupiedReport.ManifestPath) -ceq $plannedHash) `
    -Detail (Format-RunDetail -Run $run)

# Create: unsuppressed provider text and an inner exception, as an unknown failure could carry them.
$providerText = New-LifecycleScenario -Name 'stop-report-provider-text'
$null = Invoke-LifecycleRun -Scenario $providerText -Arguments @{ Action = 'Plan' }
$run = Invoke-LifecycleRun -Scenario $providerText -Arguments @{ Action = 'Create' } -Behavior @{
    FailSql = 'CreateDatabase'
    FailMessage = 'Provider text near ' + $fakeSecret
    FailInnerMessage = 'Native text ' + $fakeInnerSecret
}
$journalText = Get-JournalText -Scenario $providerText
$reportedText = Get-RunOutcomeText -Scenario $providerText -Run $run
$leaks = @(@($fakeSecret, $fakeInnerSecret, 'Password=') | Where-Object {
        $reportedText.Contains($_) -or $journalText.Contains($_)
    })
$status = Get-ScenarioStepStatus -Scenario $providerText -Name 'CreateDatabase'
Assert-True -Name 'unsuppressed provider and inner exception text reach neither the executor nor the journal' `
    -Condition ($run.Completed -and $run.Threw -and $journalText -and $leaks.Count -eq 0 -and
        @(Find-Calls -Run $run -Pattern '^Sql\.CreateDatabase$').Count -eq 1) `
    -Detail ('leaks=' + ($leaks -join '|') + '; ' + (Format-RunDetail -Run $run))
Assert-True -Name 'an unclassified failure is reported only by its exception type and numeric SQL code' -Condition (
    $run.Message -cmatch $unclassifiedReason -and $run.Message -cmatch '\bSystem\.InvalidOperationException\b' -and
    $run.Message -cmatch '\b51199\b') -Detail (Format-RunDetail -Run $run)
Assert-True -Name 'a failure journal write claimed to the executor is the Failed step on disk' -Condition (
    $run.Message -cmatch $claimsJournalWritten -and $run.Message -cnotmatch $claimsJournalWriteFailed -and
    $status -ceq 'Failed') -Detail ('CreateDatabase=' + $status + '; ' + (Format-RunDetail -Run $run))

# Create: a failure code value that is not a SQL error number is not shown.
$codeText = New-LifecycleScenario -Name 'stop-report-nonnumeric-code'
$null = Invoke-LifecycleRun -Scenario $codeText -Arguments @{ Action = 'Plan' }
$codeSentinel = 'FAKE-SENTINEL-CODE-9Z'
$run = Invoke-LifecycleRun -Scenario $codeText -Arguments @{ Action = 'Create' } `
    -Behavior @{ FailSql = 'CreateDatabase'; FailSqlNumber = $codeSentinel }
$journalKeepsCode = (Get-JournalText -Scenario $codeText).Contains($codeSentinel)
Assert-True -Name 'a non-numeric failure code value is not shown to the executor' -Condition (
    $run.Completed -and $run.Threw -and @(Find-Calls -Run $run -Pattern '^Sql\.CreateDatabase$').Count -eq 1 -and
    -not (Get-RunOutcomeText -Scenario $codeText -Run $run).Contains($codeSentinel)) `
    -Detail ('journalKeepsRawCode=' + $journalKeepsCode + '; ' + (Format-RunDetail -Run $run))
# The journal copies the code value it is given. Whether a non-numeric value is reachable depends on the only product
# producer, the Invoke-DatabaseSql catch. It runs here on an unopened connection, so the command fails before any I/O.
$producer = & {
    param($ProductFile)
    . $ProductFile
    $command = Get-Command -Name 'Invoke-DatabaseSql'
    $file = $(if ($command.CommandType -eq 'Function') { [string]$command.ScriptBlock.File } else { '' })
    $failure = $null
    $state = 'not run'
    if ([string]::Equals($file, $ProductFile, [StringComparison]::OrdinalIgnoreCase)) {
        $connection = [Data.SqlClient.SqlConnection]::new('Data Source=lpc:.\OFFLINESTUB;Initial Catalog=master')
        try {
            $null = Invoke-DatabaseSql -Connection $connection -Sql 'SELECT 1' -Result Scalar
        }
        catch {
            $failure = $_.Exception
        }
        finally {
            $state = [string]$connection.State
            $connection.Dispose()
        }
    }
    [pscustomobject]@{
        File = $file
        Failure = $failure
        State = $state
    }
} $commonFile
$producedCode = $(if ($null -ne $producer.Failure) { $producer.Failure.Data['DatabaseSqlNumber'] } else { $null })
$producedType = $(if ($null -ne $producedCode) { $producedCode.GetType().FullName } else { 'none' })
$producerStoresInt = $producer.State -ceq 'Closed' -and $null -ne $producedCode -and $producedCode -is [int]
Assert-True -Name 'the only product producer of the SQL failure code stores an integer' -Condition $producerStoresInt `
    -Detail ('producer=' + $producer.File + '; connection=' + $producer.State + '; codeType=' + $producedType)
# Kept verbatim and reachable would be a defect; kept only from synthetic input is a recorded contract limit.
$journalOutcome = $(if (-not $journalKeepsCode) {
        'PASS'
    } elseif ($producerStoresInt) {
        'OBSERVED'
    } else {
        'FAIL'
    })
Add-TestResult -Name 'the failure journal keeps a non-numeric code value only when no product producer emits one' `
    -Outcome $journalOutcome `
    -Detail ('journalKeepsRawCode=' + $journalKeepsCode + '; producerStoresInt=' + $producerStoresInt +
        '; the journal copies Exception.Data verbatim, the product producer stores provider number or 0')

# Create: the failure journal write itself fails after the original failure.
$failureWrite = New-LifecycleScenario -Name 'stop-report-failure-journal-write'
$null = Invoke-LifecycleRun -Scenario $failureWrite -Arguments @{ Action = 'Plan' }
$run = Invoke-LifecycleRun -Scenario $failureWrite -Arguments @{ Action = 'Create' } `
    -Behavior @{ FailSql = 'CreateDatabase'; PendingAt = 'CreateDatabase' }
$status = Get-ScenarioStepStatus -Scenario $failureWrite -Name 'CreateDatabase'
$pendingText = Get-PendingWriteText -Scenario $failureWrite
Assert-True -Name 'a failed failure-journal write keeps the original SQL code and claims no journal record' `
    -Condition ($run.Completed -and $run.Threw -and $run.Message -cmatch '\b51199\b' -and
        $run.Message -cmatch $claimsJournalWriteFailed -and $run.Message -cmatch $claimsUnconfirmed -and
        $run.Message -cnotmatch $claimsJournalWritten) -Detail (Format-RunDetail -Run $run)
Assert-True -Name 'after a failed failure-journal write the step stays Pending and the interrupted write is kept' `
    -Condition (@(Find-Calls -Run $run -Pattern '^Sql\.CreateDatabase$').Count -eq 1 -and $status -ceq 'Pending' -and
        $pendingText -ceq $interruptedWrite) -Detail ('CreateDatabase=' + $status + '; pending=' + $pendingText)

# Install: the completion write of a step whose side effect already ran fails. The execution plan has the executor
# compare exit, journal and identity after each command, so the message must not misstate the durable step state.
$completionWrite = New-LifecycleScenario -Name 'stop-report-completion-write'
$null = Invoke-LifecycleRun -Scenario $completionWrite -Arguments @{ Action = 'Plan' }
$null = Invoke-LifecycleRun -Scenario $completionWrite -Arguments @{ Action = 'Create' }
$before = Get-ManifestState -Scenario $completionWrite
$run = Invoke-LifecycleRun -Scenario $completionWrite -Arguments @{ Action = 'Install'; Phase = 'Baseline001' } `
    -Behavior @{ StubMigrations = $true; SchemaRows = $baselineRows; PendingAt = 'ReadSchemaVersion' }
$status = Get-ScenarioStepStatus -Scenario $completionWrite -Name 'InstallBaseline001'
$pendingText = Get-PendingWriteText -Scenario $completionWrite
Assert-True -Name 'a failed completion write is not reported as a non-Pending step while the journal holds Pending' `
    -Condition ($before -ceq 'Created' -and $run.Completed -and $run.Threw -and $status -ceq 'Pending' -and
        @(Find-Calls -Run $run -Pattern '^Migrations\.Baseline001$').Count -eq 1 -and
        $pendingText -ceq $interruptedWrite -and $run.Message -cnotmatch $claimsJournalWritten -and
        $run.Message -cnotmatch '(?i)\bstep is not pending\b') `
    -Detail ('before=' + $before + '; InstallBaseline001=' + $status + '; ' + (Format-RunDetail -Run $run))

# Install: the instance reports another identity for the exact name than the journal recorded.
$identityChange = New-LifecycleScenario -Name 'stop-report-identity-change'
$null = Invoke-LifecycleRun -Scenario $identityChange -Arguments @{ Action = 'Plan' }
$null = Invoke-LifecycleRun -Scenario $identityChange -Arguments @{ Action = 'Create' }
$identityReady = Test-CreatedWithIdentity -Scenario $identityChange
if ($identityReady) {
    # Fixture edit: only the recorded GUID differs from the GUID the harness reports for the database.
    $manifest = Read-LifecycleManifest -Scenario $identityChange
    $manifest.DatabaseIdentity.DatabaseGuid = '0B3E1A52-5D0E-4C55-9C8E-2B7E3C1D4A61'
    Write-FixtureText -Path $identityChange.ManifestPath -Text ($manifest | ConvertTo-Json -Depth 20)
}
$changedHash = Get-FileHashHex -Path $identityChange.ManifestPath
$run = Invoke-LifecycleRun -Scenario $identityChange -Arguments @{ Action = 'Install'; Phase = 'Baseline001' } `
    -Behavior @{ StubMigrations = $true; SchemaRows = $baselineRows }
Assert-True -Name 'an unexpected database identity at Install is reported as an identity stop, not unclassified' `
    -Condition ($identityReady -and $run.Completed -and $run.Threw -and
        @(Find-Calls -Run $run -Pattern '^Migrations\.').Count -eq 0 -and
        (Get-FileHashHex -Path $identityChange.ManifestPath) -ceq $changedHash -and
        $run.Message -cmatch '(?i)\bidentity\b' -and $run.Message -cnotmatch $unclassifiedReason) `
    -Detail ('identityReady=' + $identityReady + '; ' + (Format-RunDetail -Run $run))

# Cleanup: refused before deletion with a classified reason; nothing is claimed as recorded.
$prereject = New-CleanupReadyScenario -Name 'cleanup-report-prereject'
$ready = Test-CreatedWithIdentity -Scenario $prereject
$reviewed = Get-FileHashHex -Path $prereject.ManifestPath
$run = Invoke-LifecycleRun -Scenario $prereject -Entry Remove `
    -Arguments (Get-RemoveArguments -Scenario $prereject -Mode 'Execute' -ManifestHash ('A' * 64))
Assert-True -Name 'a cleanup refused before deletion says so with a classified reason and claims no journal record' `
    -Condition ($ready -and $run.Completed -and $run.Threw -and $run.Message -cmatch $claimsStoppedBeforeDeletion -and
        $run.Message -cnotmatch $claimsDeletionAttempted -and $run.Message -cmatch $claimsNoJournalWrite -and
        $run.Message -cnotmatch $claimsJournalWritten -and $run.Message -cnotmatch $unclassifiedReason -and
        (Get-FileHashHex -Path $prereject.ManifestPath) -ceq $reviewed -and
        @(Find-Calls -Run $run -Pattern '^(Sql\.Drop|RemoveLocalUser)').Count -eq 0) `
    -Detail ('ready=' + $ready + '; ' + (Format-RunDetail -Run $run))

# Cleanup: the plan's account name now belongs to an account with another SID than the journal recorded.
$sidChange = New-CleanupReadyScenario -Name 'cleanup-report-sid-change'
$ready = Test-CreatedWithIdentity -Scenario $sidChange
if ($ready) {
    $manifest = Read-LifecycleManifest -Scenario $sidChange
    $manifest.WindowsAccountSid = $recoveryAccountSid
    Write-FixtureText -Path $sidChange.ManifestPath -Text ($manifest | ConvertTo-Json -Depth 20)
}
$reviewed = Get-FileHashHex -Path $sidChange.ManifestPath
$otherAccount = @([pscustomobject]@{ Name = $sidChange.RecoveryLocalName; Sid = 'S-1-5-21-1-2-3-1999' })
$run = Invoke-LifecycleRun -Scenario $sidChange -Entry Remove -Behavior @{ LocalUsers = $otherAccount } `
    -Arguments (Get-RemoveArguments -Scenario $sidChange -Mode 'Execute')
Assert-True -Name 'a recorded Windows account now holding another SID stops cleanup before any deletion' -Condition (
    $ready -and $run.Completed -and $run.Threw -and
    @(Find-Calls -Run $run -Pattern '^(Sql\.Drop|RemoveLocalUser)').Count -eq 0 -and
    (Get-FileHashHex -Path $sidChange.ManifestPath) -ceq $reviewed -and
    $run.Message -cmatch '(?i)\bwindows account\b' -and $run.Message -cnotmatch $unclassifiedReason -and
    $run.Message -cmatch $claimsStoppedBeforeDeletion) -Detail ('ready=' + $ready + '; ' + (Format-RunDetail -Run $run))

# Cleanup: the CleanupStarted journal write fails, before any deletion.
$startWrite = New-CleanupReadyScenario -Name 'cleanup-report-start-write'
$ready = Test-CreatedWithIdentity -Scenario $startWrite
$reviewed = Get-FileHashHex -Path $startWrite.ManifestPath
$run = Invoke-LifecycleRun -Scenario $startWrite -Entry Remove -Behavior @{ PendingAt = 'LedgerCount' } `
    -Arguments (Get-RemoveArguments -Scenario $startWrite -Mode 'Execute')
Assert-True -Name 'a failed CleanupStarted write reports no deletion and an unconfirmed journal, journal unchanged' `
    -Condition ($ready -and $run.Completed -and $run.Threw -and $run.Message -cmatch $claimsStoppedBeforeDeletion -and
        $run.Message -cmatch $claimsJournalWriteFailed -and $run.Message -cmatch $claimsUnconfirmed -and
        $run.Message -cnotmatch $claimsJournalWritten -and
        (Get-FileHashHex -Path $startWrite.ManifestPath) -ceq $reviewed -and
        (Get-PendingWriteText -Scenario $startWrite) -ceq $interruptedWrite -and
        @(Find-Calls -Run $run -Pattern '^Sql\.Drop').Count -eq 0) `
    -Detail ('ready=' + $ready + '; ' + (Format-RunDetail -Run $run))

# Cleanup: DROP was attempted and failed, then the failure journal write fails too.
$dropWrite = New-CleanupReadyScenario -Name 'cleanup-report-drop-write'
$ready = Test-CreatedWithIdentity -Scenario $dropWrite
$run = Invoke-LifecycleRun -Scenario $dropWrite -Entry Remove `
    -Behavior @{ FailSql = 'DropDatabase'; PendingAt = 'DropDatabase' } `
    -Arguments (Get-RemoveArguments -Scenario $dropWrite -Mode 'Execute')
$manifest = Read-LifecycleManifest -Scenario $dropWrite
$cleanupSteps = @(if ($null -ne $manifest.Cleanup) { $manifest.Cleanup.Steps })
Assert-True -Name 'an attempted deletion whose failure journal write fails is reported as attempted and unconfirmed' `
    -Condition ($ready -and $run.Completed -and $run.Threw -and $run.Message -cmatch $claimsDeletionAttempted -and
        $run.Message -cmatch $claimsJournalWriteFailed -and $run.Message -cmatch $claimsUnconfirmed -and
        $run.Message -cnotmatch $claimsJournalWritten -and $run.Message -cmatch '\b51199\b') `
    -Detail ('ready=' + $ready + '; ' + (Format-RunDetail -Run $run))
Assert-True -Name 'that journal keeps CleanupStarted with its DROP step Pending and the interrupted write' -Condition (
    $manifest.State -ceq 'CleanupStarted' -and $null -ne $manifest.Cleanup -and
    $manifest.Cleanup.State -ceq 'Pending' -and $cleanupSteps.Count -eq 1 -and
    $cleanupSteps[0].Name -ceq 'DropDatabase' -and $cleanupSteps[0].Status -ceq 'Pending' -and
    (Get-PendingWriteText -Scenario $dropWrite) -ceq $interruptedWrite) `
    -Detail ('state=' + $manifest.State + '; cleanup=' + ($manifest.Cleanup | ConvertTo-Json -Compress -Depth 5))

# Cleanup: the failed DROP above, whose failure journal write succeeded. Its later refused runs left the journal at
# $startedHash, so the journal read here is the one that failed run wrote.
$dropManifest = Read-LifecycleManifest -Scenario $dropFailure
$dropSteps = @(if ($null -ne $dropManifest.Cleanup) { $dropManifest.Cleanup.Steps })
Assert-True -Name 'an attempted cleanup reported as recorded is Failed on disk with its deletion outcome unconfirmed' `
    -Condition ($dropReady -and (Get-FileHashHex -Path $dropFailure.ManifestPath) -ceq $startedHash -and
        $failedDrop.Message -cmatch $claimsJournalWritten -and $failedDrop.Message -cmatch $claimsDeletionAttempted -and
        $failedDrop.Message -cmatch $claimsUnconfirmed -and $null -ne $dropManifest.Cleanup -and
        $dropManifest.Cleanup.State -ceq 'Failed' -and $dropSteps.Count -eq 1 -and $dropSteps[0].Status -ceq 'Failed') `
    -Detail (Format-RunDetail -Run $failedDrop)

# ---- The real Assert-TestEnvironmentLocalAccountAbsent with only the OS Get-LocalUser cmdlet replaced. The harness
# and Set-OfflineStubs replace this helper, so its own branches run here: the product file is dot-sourced again in a
# child scope and a function in that scope shadows the cmdlet (functions win over cmdlets in command lookup). Both
# resolutions are checked before the helper runs. No real account is looked up.
$accountPlan = New-DraftPlanObject -Root (Join-Path $script:SuiteRoot 'local-account')
$suiteFile = [IO.Path]::GetFullPath($PSCommandPath)

function Invoke-RealLocalAccountAbsent {
    param([Parameter(Mandatory)][ValidateSet('Exists', 'NotFound', 'LookupFailed')][string]$Lookup)
    return & {
        param($Plan, $LookupKind, $ProductFile, $StubFile)
        . $ProductFile
        $lookups = New-Object 'Collections.Generic.List[string]'
        function Get-LocalUser {
            [CmdletBinding()]
            param([string]$Name)
            # Like the OS cmdlet, a missing or unreadable account is a non-terminating error record.
            $lookups.Add($Name)
            if ($LookupKind -ceq 'Exists') {
                return [pscustomobject]@{
                    Name = $Name
                    SID = [Security.Principal.SecurityIdentifier]::new('S-1-5-21-1-2-3-1005')
                }
            }
            $notFound = $LookupKind -ceq 'NotFound'
            $errorId = $(if ($notFound) { 'UserNotFound' } else { 'AccessDenied' })
            $category = $(if ($notFound) { 'ObjectNotFound' } else { 'PermissionDenied' })
            $PSCmdlet.WriteError([Management.Automation.ErrorRecord]::new(
                    [InvalidOperationException]::new('Offline stub lookup result: ' + $errorId),
                    $errorId,
                    [Management.Automation.ErrorCategory]$category,
                    $Name))
        }
        $stub = Get-Command -Name 'Get-LocalUser'
        $helper = Get-Command -Name 'Assert-TestEnvironmentLocalAccountAbsent'
        $stubFile = $(if ($stub.CommandType -eq 'Function') { [string]$stub.ScriptBlock.File } else { '' })
        $helperFile = $(if ($helper.CommandType -eq 'Function') { [string]$helper.ScriptBlock.File } else { '' })
        $resolved = [string]::Equals($stubFile, $StubFile, [StringComparison]::OrdinalIgnoreCase) -and
            [string]::Equals($helperFile, $ProductFile, [StringComparison]::OrdinalIgnoreCase)
        $failure = $null
        if ($resolved) {
            # The helper must stop on its own, not because the caller turned every error into a terminating one.
            $ErrorActionPreference = 'Continue'
            try {
                Assert-TestEnvironmentLocalAccountAbsent -Contract $Plan
            }
            catch {
                $failure = $_.Exception
            }
        }
        [pscustomobject]@{
            Resolved = $resolved
            Resolution = 'Get-LocalUser=' + $stub.CommandType + ':' + $stubFile + ', helper=' + $helper.CommandType +
                ':' + $helperFile
            Failure = $failure
            Lookups = @($lookups)
        }
    } $accountPlan $Lookup $commonFile $suiteFile
}

function Format-AccountCase {
    param([Parameter(Mandatory)]$Case)
    $message = $(if ($null -ne $Case.Failure) { $Case.Failure.Message } else { 'none' })
    return ('resolved={0}; lookups={1}; failure=<{2}>' -f $Case.Resolved, (@($Case.Lookups) -join ','), $message)
}

$accountCases = [ordered]@{}
foreach ($lookup in @('Exists', 'NotFound', 'LookupFailed')) {
    $accountCases[$lookup] = Invoke-RealLocalAccountAbsent -Lookup $lookup
}
$resolutions = @($accountCases.Keys | ForEach-Object { $_ + ': ' + $accountCases[$_].Resolution })
$unresolved = @($accountCases.Values | Where-Object { -not $_.Resolved })
Assert-True -Name 'the real account-absence helper and the Get-LocalUser stub resolve as intended before any call' `
    -Condition ($unresolved.Count -eq 0) -Detail ($resolutions -join '; ')
$exists = $accountCases['Exists']
$notFound = $accountCases['NotFound']
$lookupFailed = $accountCases['LookupFailed']
Assert-True -Name 'an existing exact Windows account name stops the real helper as occupied' -Condition (
    $exists.Resolved -and $null -ne $exists.Failure -and $exists.Failure.Message -cmatch '(?i)\boccupied\b' -and
    @($exists.Lookups).Count -eq 1 -and @($exists.Lookups)[0] -ceq $accountPlan.RecoveryLocalName) `
    -Detail (Format-AccountCase -Case $exists)
Assert-True -Name 'an exact UserNotFound lookup proves the account name absent in the real helper' -Condition (
    $notFound.Resolved -and $null -eq $notFound.Failure -and @($notFound.Lookups).Count -eq 1) `
    -Detail (Format-AccountCase -Case $notFound)
Assert-True -Name 'any other lookup error stops the real helper as unproven absence, not as occupied' -Condition (
    $lookupFailed.Resolved -and $null -ne $lookupFailed.Failure -and @($lookupFailed.Lookups).Count -eq 1 -and
    $lookupFailed.Failure.Message -cmatch '(?i)\babsent\b' -and
    $lookupFailed.Failure.Message -cnotmatch '(?i)\boccupied\b') `
    -Detail (Format-AccountCase -Case $lookupFailed)
$occupiedSummary = ''
$unprovenSummary = ''
$extendedSummary = ''
if ($null -ne $exists.Failure -and $null -ne $lookupFailed.Failure) {
    $occupiedSummary = Get-TestEnvironmentFailureSummary -Exception $exists.Failure
    $unprovenSummary = Get-TestEnvironmentFailureSummary -Exception $lookupFailed.Failure
    $extended = [InvalidOperationException]::new($exists.Failure.Message + ' ' + $fakeSecret)
    $extendedSummary = Get-TestEnvironmentFailureSummary -Exception $extended
}
Assert-True -Name 'both real account stop reasons reach the executor summary classified and distinct' -Condition (
    $occupiedSummary -cmatch '(?i)\boccupied\b' -and $unprovenSummary -cmatch '(?i)\babsent\b' -and
    $occupiedSummary -cnotmatch $unclassifiedReason -and $unprovenSummary -cnotmatch $unclassifiedReason) `
    -Detail ('occupied=<' + $occupiedSummary + '>; unproven=<' + $unprovenSummary + '>')
Assert-True -Name 'a known stop reason extended with other text is not echoed to the executor' -Condition (
    $extendedSummary -and -not $extendedSummary.Contains($fakeSecret) -and
    $extendedSummary -cmatch $unclassifiedReason) `
    -Detail $extendedSummary

# ---- Every run stayed inside the shadowed boundary set and the harness ran the product each time.
$escaped = @($script:AllRuns | Where-Object { $_.HarnessExit -ne 0 -or -not $_.Completed })
$allCalls = @($script:AllRuns | ForEach-Object { $_.Calls })
$blockedCalls = @($allCalls | Where-Object { $_.Name -cmatch '^(Blocked\.|Sql\.Unexpected)' })
$escapedNames = @($escaped | ForEach-Object { $_.Scenario + '/' + $_.Name }) -join ','
$blockedNames = @($blockedCalls | ForEach-Object { $_.Run + ':' + $_.Name }) -join ','
Assert-True -Name 'every product run completed inside the harness without reaching a blocked boundary' -Condition (
    $script:AllRuns.Count -gt 0 -and $escaped.Count -eq 0 -and $blockedCalls.Count -eq 0) `
    -Detail ('runs=' + $script:AllRuns.Count + '; escaped=' + $escapedNames + '; blocked=' + $blockedNames)

Complete-TestSuite
