using System;
using System.Collections.Generic;
using System.Data;
using System.Text;

namespace PacketGenerator
{
    internal class PacketFormat
    {
        // {0} : 패킷 등록 코드
        public static string managerFormat =
@"using ServerCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

public class PacketManager
{{
    #region SINGLETON
#nullable enable
    static PacketManager? _instance = new PacketManager();
#nullable disable

    public static PacketManager Instance
    {{
        get {{ return _instance; }}
        private set {{ }}
    }}
    #endregion
    
    PacketManager()
    {{
        Register();
    }}

    // < 프로토콜 ID, 패킷 처리 콜백>
    Dictionary<ushort, Func<PacketSession, ArraySegment<byte>, IPacket>> m_MakeFunc = new Dictionary<ushort, Func<PacketSession, ArraySegment<byte>, IPacket>>();
    Dictionary<ushort, Action<PacketSession,IPacket>> m_Handler = new Dictionary<ushort, Action<PacketSession, IPacket>>();

    public void Register()
    {{
        {0}
    }}
        
    public void OnRecvPacket(PacketSession session,
        ArraySegment<byte> buffer,
        Action<PacketSession, IPacket> onRecvCallBack = null)
    {{
        ushort count = 0;

        ushort size = BitConverter.ToUInt16(buffer.Array, buffer.Offset);
        count += 2;

        ushort id = BitConverter.ToUInt16(buffer.Array, buffer.Offset + 2);
        count += 2;

        Func<PacketSession, ArraySegment<byte>, IPacket> func = null;
        if(m_MakeFunc.TryGetValue(id, out func))
        {{
            IPacket packet = func.Invoke(session, buffer);

            if (onRecvCallBack != null)
                onRecvCallBack.Invoke(session, packet);
            else
                HandlePacket(session, packet);
        }}

        // System.Console.WriteLine($""Recv PacketId: {{id}}, Size: {{size}}"");
    }}

    T MakePacket<T>(PacketSession session, ArraySegment<byte> buffer)
        where T : IPacket, new()
    {{
        T packet = new T();
        packet.Read(buffer);

        return packet;
    }}

    public void HandlePacket(PacketSession _session, IPacket _packet)
    {{
        Action<PacketSession, IPacket> action = null;
        if (m_Handler.TryGetValue(_packet.Protocol, out action))
            action.Invoke(_session, _packet);
    }}
}}";

        // {0} : 패킷 이름
        public static string mangerRegisterFormat =
@"
        m_MakeFunc.Add((ushort)PacketID.{0}, MakePacket<{0}>);
        m_Handler.Add((ushort)PacketID.{0}, PacketHandler.{0}Handler);";
        // {0} : 패킷 이름/번호 목록
        // {1} : 패킷 목록
        public static string fileFormat =
@"// <auto-generated />
// 본 파일은 99_Tools/PacketGenerator/PDL.xml로부터 자동 생성됨. 직접 수정 X.
//
// **책임 단위 분리/통합** (ADR-012, Y2 갈래 + Phase 07 책임 단위 정제):
//   - 패킷 정의 (이 파일) = 양쪽 통합 (Shared.Protocol). 와이어 포맷은 환경 무관.
//   - socket 인프라 (Connector/Listener/Session/Buffer) = 양쪽 분리 (ADR-012).
//   - 핸들러 (GameSession/UnityClientSession) = 양쪽 분리.
//
// 따라서 본 파일은 SendBufferHelper / ServerCore 의존 X. Write()는 byte[] 반환만,
// 호출자(핸들러)가 자기 SendBuffer로 marshalling.
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.Text;

namespace Shared.Protocol;

public enum PacketID : ushort
{{
    {0}
}}

public interface IPacket
{{
    ushort Protocol {{ get; }} // 패킷 ID 반환

    void Read(ArraySegment<byte> _Segment); // [size:2][id:2][payload] 통째 읽기
    ArraySegment<byte> Write();             // [size:2][id:2][payload] 통째 byte[] 반환
}}


{1}
";
        // {0} : 패킷 이름
        // {1} : 패킷 번호
        public static string packetEnumFormat =
@"{0} = {1},";


        // {0} : 패킷 이름
        // {1} : 패킷 멤버 변수들
        // {2} : 멤버 변수 Read
        // {3} : 멤버 변수 Write
        public static string packetFormat =
@"public class {0} : IPacket // {0} 패킷
{{
    // 멤버 변수들
    {1}
    public ushort Protocol {{ get {{ return (ushort)PacketID.{0}; }} }}

    public void Read(ArraySegment<byte> _Segment)
    {{
        // _Segment = [size:2][id:2][payload...] 통째.
        // PacketSession이 이미 size 헤더 검증 후 한 패킷 단위로 넘김.
        ushort count = 0;
        ReadOnlySpan<byte> s = new ReadOnlySpan<byte>(_Segment.Array, _Segment.Offset, _Segment.Count);

        count += sizeof(ushort); // size 헤더 skip
        count += sizeof(ushort); // packet id 헤더 skip

        // 멤버 읽기
        {2}
    }}


    public ArraySegment<byte> Write()
    {{
        // SendBufferHelper 의존 X — 새 byte[] 직접 할당 후 반환 (Phase 07 책임 단위 분리).
        // 호출자(서버 GameSession / Unity UnityClientSession)가 자기 SendBuffer로 marshalling.
        // BinaryPrimitives.*LittleEndian 명시 (BitConverter는 호스트 endian 의존).
        byte[] segment = new byte[ushort.MaxValue];
        ushort count = 0;
        bool success = true;
        Span<byte> s = new Span<byte>(segment);

        count += sizeof(ushort); // size 자리 예약 (마지막에 채움)

        success &= BinaryPrimitives.TryWriteUInt16LittleEndian(s.Slice(count, s.Length - count), (ushort)PacketID.{0});
        count += sizeof(ushort);

        // 멤버 쓰기
        {3}

        // 최종 size 기록
        success &= BinaryPrimitives.TryWriteUInt16LittleEndian(s, count);

        if (!success)
            return default;

        return new ArraySegment<byte>(segment, 0, count);
    }}
}}

";
        // {0} : 변수 타입
        // {1} : 변수 이름
        public static string MemberFormat =
@"public {0} {1};";


        // {0} : 리스트 이름 [대문자]
        // {1} : 리스트 이름 [소문자]
        // {2} : 멤버 변수들
        // {3} : 멤버 변수 Read
        // {4} : 멤버 변수 Write
        public static string MemberListFormat =
@"
public struct {0}
{{
#if NET10_0_OR_GREATER
    public {0}()
    {{
        // {0} 구조체 생성자
    }}
#endif

    // {0}List 멤버 변수들
    {2}

#if !NET_LEGACY
    public void Read(ReadOnlySpan<byte> s, ref ushort count)
    {{
        // {0} 리스트 멤버 읽기
        // C++ 서버에서는 더 최적화 가능하지만, C#에서는 BitConverter로 간단히 읽는 방법을 사용

        {3}
    }}
#else
    public void Read(ArraySegment<byte> s, ref ushort count)
    {{
        // {0} 리스트 멤버 읽기
        // C++ 서버에서는 더 최적화 가능하지만, C#에서는 BitConverter로 간단히 읽는 방법을 사용

        {3}
    }}
#endif
    
#if !NET_LEGACY
    public bool Write(Span<byte> s, ref ushort count)
    {{
        bool success = true; // 쓰기 성공 여부

        // {0} 리스트 멤버 쓰기

        {4}

        return success;
    }}
#else
    public bool Write(ArraySegment<byte> s, ref ushort count)
    {{
        bool success = true; // 쓰기 성공 여부

        // {0} 리스트 멤버 쓰기

        {4}

        return success;
    }}
#endif

}}

public List<{0}> {1}s = new List<{0}>(); // {0} 리스트";

        // {0} : 변수 이름
        // {1} : BinaryPrimitives.Read*LittleEndian 의 * 부분 (Int16/UInt16/Int32/UInt32/Int64/UInt64/Single/Double)
        // {2} : 변수 형식 (sizeof 계산용)
        public static string ReadFormat =
@"// {0} 읽기 (LittleEndian 명시 — wire format 약속)
this.{0} = BinaryPrimitives.Read{1}LittleEndian(s.Slice(count, s.Length - count));
count += sizeof({2});
";
        // byte/sbyte 1바이트 직접 인덱싱.
        // Phase 04 정정: 옛 ServerDev `_Segment.Array[Offset+count]`/`Segment.Array[...]` 패턴은
        // 새 Read/Write 메서드 변수와 안 맞음 → 현 메서드의 `s` (ReadOnlySpan/Span<byte>) 직접 사용.
        //
        // {0} : 변수 이름
        // {1} : 변수 형식
        public static string ReadByteFormat =
@"// {0} 읽기
this.{0} = ({1})s[count];
count += sizeof({1});
";

        // {0} : 변수 이름
        // M3 Phase 02 정정 (Codex pre-M3 감사 결함 박제 — bool/string broken 두 번째):
        //   - 옛 BitConverter.ToUInt16(Span)은 호스트 endian 의존 → 헌법 #2 LittleEndian 약속 위반. BinaryPrimitives로 통일.
        //   - 옛 NET_LEGACY 분기는 .Array 접근 시도(Span은 .Array 없음) → 컴파일 깨짐. 본 프로젝트는 NET_LEGACY 안 박으니 분기 제거.
        //   - Encoding.Unicode.GetString(ReadOnlySpan<byte>) 시그니처는 .NET Standard 2.1 지원.
        // S_HandshakeResult.reason이 첫 실수요자.
        public static string ReadStringFormat =
@"// {0} 문자열 읽기 (Length prefix UInt16 LittleEndian + UTF-16 payload)
ushort {0}Len = BinaryPrimitives.ReadUInt16LittleEndian(s.Slice(count, s.Length - count));
count += sizeof(ushort);
this.{0} = Encoding.Unicode.GetString(s.Slice(count, {0}Len));
count += {0}Len;
";

        // {0} : 리스트 이름 [대문자]
        // {1} : 리스트 이름 [소문자]
        public static string ReadListFormat =
@"#if !NET_LEGACY
// {0} 리스트 읽기
this.{1}s.Clear();
ushort {1}Len = BitConverter.ToUInt16(s.Slice(count, s.Length - count));
count += sizeof(ushort);
for (int i = 0; i < {1}Len; i++)
{{
    {0} {1} = new {0}();
    {1}.Read(s, ref count);
    {1}s.Add({1});
}}
#else
this.{1}s.Clear();
ushort {1}Len = BitConverter.ToUInt16(s.Array, s.Offset + count);
count += sizeof(ushort);
for (int i = 0; i < {1}Len; i++)
{{
    {0} {1} = new {0}();
    {1}.Read(s, ref count);
    {1}s.Add({1});
}}
#endif
";

        // float/double 우회 — .NET Standard 2.1엔 BinaryPrimitives.Read/WriteSingleLittleEndian이
        // 없어 빌드 실패. BitConverter.Int32BitsToSingle / SingleToInt32Bits를 경유한다.
        // .NET 5+ 환경(서버 .NET 10)에선 변환 비용 미미. 양쪽 어셈블리 동일 wire format.
        //
        // {0} : 변수 이름
        public static string ReadFloatFormat =
@"// {0} 읽기 (LittleEndian 명시 — .NET Standard 2.1 호환을 위해 Int32Bits 경유)
this.{0} = BitConverter.Int32BitsToSingle(BinaryPrimitives.ReadInt32LittleEndian(s.Slice(count, s.Length - count)));
count += sizeof(float);
";
        // {0} : 변수 이름
        public static string WriteFloatFormat =
@"// {0} 쓰기 (LittleEndian 명시 — .NET Standard 2.1 호환을 위해 Int32Bits 경유)
success &= BinaryPrimitives.TryWriteInt32LittleEndian(s.Slice(count, s.Length - count), BitConverter.SingleToInt32Bits(this.{0}));
count += sizeof(float);
";

        // {0} : 변수 이름
        // {1} : BinaryPrimitives.Write*LittleEndian 의 * 부분 (Int16/UInt16/Int32/UInt32/Int64/UInt64/Single/Double)
        // {2} : 변수 형식 (sizeof 계산용)
        public static string WriteFormat =
@"// {0} 쓰기 (LittleEndian 명시 — wire format 약속)
success &= BinaryPrimitives.TryWrite{1}LittleEndian(s.Slice(count, s.Length - count), this.{0});
count += sizeof({2});
";

        // {0} : 변수 이름
        // {1} : 변수 형식
        public static string WriteByteFormat =
@"// {0} 쓰기
s[count] = (byte)this.{0};
count += sizeof({1});
";

        // M3 Phase 02 신설 (Codex pre-M3 감사 결함 박제 — bool broken):
        //   - bool은 BinaryPrimitives에 LittleEndian 변종 부재 (1바이트라 endian 무관).
        //   - 옛 묶음(short/ushort/uint/...)에 같이 들어가 ReadBooleanLittleEndian 호출 → 컴파일 깨짐.
        //   - 정정: byte 패턴 별도 — 0=false, 1=true 매핑. sizeof(bool)=1 C# 보장.
        //   - S_HandshakeResult.ok가 첫 실수요자.
        //
        // {0} : 변수 이름
        public static string ReadBoolFormat =
@"// {0} 읽기 (1바이트, 0 = false / 그 외 = true)
this.{0} = s[count] != 0;
count += sizeof(bool);
";

        // {0} : 변수 이름
        public static string WriteBoolFormat =
@"// {0} 쓰기 (1바이트, false → 0 / true → 1)
s[count] = (byte)(this.{0} ? 1 : 0);
count += sizeof(bool);
";

        // {0} : 변수 이름
        // M3 Phase 02 정정 (Codex pre-M3 감사 결함 박제):
        //   - 옛 코드는 `Segment.Array` / `Segment.Offset` 참조 (변수 미존재 — Phase 07 책임 단위 분리 후 변수명 `s`). 컴파일 깨짐.
        //   - 옛 NET_LEGACY 분기에 `{0}len` 오타까지(소문자) — 두 번째 결함.
        //   - 정정: GetByteCount + GetBytes(ReadOnlySpan<char>, Span<byte>) 패턴 (.NET Standard 2.1 지원).
        //   - GetByteCount는 모든 .NET 지원. GetBytes(span, span)는 alloc 없음.
        //   - Length prefix는 BinaryPrimitives.TryWriteUInt16LittleEndian으로 헌법 #2 정합.
        public static string WriteStringFormat =
@"// {0} 문자열 쓰기 (Length prefix UInt16 LittleEndian + UTF-16 payload)
ushort {0}Len = (ushort)Encoding.Unicode.GetByteCount(this.{0});
success &= BinaryPrimitives.TryWriteUInt16LittleEndian(s.Slice(count, s.Length - count), {0}Len);
count += sizeof(ushort);
Encoding.Unicode.GetBytes(this.{0}.AsSpan(), s.Slice(count, s.Length - count));
count += {0}Len;
";

        // {0} : 리스트 이름 [대문자]
        // {1} : 리스트 이름 [소문자]
        public static string WriteListFormat =
@"#if !NET_LEGACY
// {0} 리스트 쓰기
success &= BitConverter.TryWriteBytes(s.Slice(count, s.Length - count), (ushort)this.{1}s.Count);
count += sizeof(ushort);
foreach ({0} {1} in this.{1}s)
    success &= {1}.Write(s, ref count);
#else
// {0} 리스트 쓰기
Array.Copy(BitConverter.GetBytes((ushort)this.{1}s.Count), 0, Segment.Array, Segment.Offset + count, sizeof(ushort));
count += sizeof(ushort);
foreach ({0} {1} in this.{1}s)
    {1}.Write(Segment, ref count);
#endif
";
    }
}
